### ISSUE TITLE
Missing PRs ?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#10]
I'm not sure but looking at the "fork date", this repo seems to miss:

Done: https://github.com/ActiveForums/ActiveForums/pull/457
Done: https://github.com/ActiveForums/ActiveForums/pull/456
Already in this repo: https://github.com/ActiveForums/ActiveForums/pull/455
https://github.com/ActiveForums/ActiveForums/pull/440

I'll check at my own PRs and ask @EPTamminga about his

**Comment by hismightiness** [comment]
@Timo-Breumelhof Do you plan on merging those PRs or should someone else try to do it for you?

**Comment by Timo-Breumelhof** [comment]
@hismightiness I can do it myself, but it will be next week in that case.

**Comment by hismightiness** [comment]
Sounds good.  I'd rather you do it since you know what you did and why, as well as get credit for it.  :)

**Comment by Timo-Breumelhof** [comment]
OK :-)

**Comment by Timo-Breumelhof** [comment]
@hismightiness is this one (your PR) already included in the current repo? 
https://github.com/ActiveForums/ActiveForums/pull/440

**Comment by hismightiness** [comment]
Kind of... The breadcrumbs are there, but not the way I did them originally.  :)

**Comment by Timo-Breumelhof** [comment]
Step 1: https://github.com/ActiveForums/ActiveForums/pull/450 done

**Comment by Timo-Breumelhof** [comment]
Done: ActiveForums/ActiveForums#457

**Comment by Timo-Breumelhof** [comment]
fixed by #16 
fixed by #17
