### ISSUE TITLE
ENH: Link forum/thread to moderation page

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/Dnn.CommunityForums#1041]
## Feature Request
**Add a link to the thread on the moderation page**
It would be very helpful for moderators to have a link to the forum/thread where the post to moderate can be found. Just to check if someone just copied another post and added a spam link...

**Comment by johnhenley** [comment]
@MaiklT I had thought about this when adding the ability to moderate from the DNN notifications, and rather than add a link to the specific post, just added a generic link to the forums moderation page. Do you think it is a security risk to have a link to a post that requires moderation?

**Comment by MaiklT** [comment]
Well, I did not mean the actual post to moderate, but the thread itself. Background: Some spammers copy a reasonable answer from the thread, so the post looks good, but at the end or somewhere in the middle they add a link that goes to something different. It is much easier to identify such things when you can see the thread and the posts before.

**Comment by johnhenley** [comment]
Do after #1112

**Comment by Timo-Breumelhof** [comment]
Link the user to the user profile would be nice too :-)
