### ISSUE TITLE
Emoticons broken after editing a post

### ISSUE THREAD

**Issue by JanDr2** [DNNCommunity/Dnn.CommunityForums#105]
## Describe the bug
When editing a post containing an emoji, the text editor replaces the emoji with a "<img ... />" tag. When saving the post, the "<" and ">" characters now contained in the post get encoded as "&lt;" and "&gt;" respectively. When viewing the edited post, instead of the emoji the "<img ... />" tag can be seen.

## Software Versions
- DNN: 09.10.01
- Module: 06.06.00

## To Reproduce
1. Create a new post containing an emoji
2. Click on 'Edit' to edit the post
3. Save the post without making any changes
4. See the edited post now containing the "<img ... />" tag instead of the emoji
5. Click on 'Edit' again to see the "<" and ">" brackets replaced with "&lt;" and "&gt;" entities in the post contents.

## Expected behavior
Editing a post should preserve the emoji in the post.

## Error log
N/A

**Comment by Timo-Breumelhof** [comment]
This might be also due to the settings of the CKEditor, which configuration are you using?
Is this still an issue when you use Full?

**Comment by JanDr2** [comment]
CKEditor is set to "Full" for Administrators and "Basic" for everyone else. This issue is observed in both cases. See the attached screenshot which shows the first and last tag bracket of the "img" tag being changed into their HTML-encoded equivalents (&lt; and &gt; respectively) after editing a post that contains an emoji.
![AF_1](https://user-images.githubusercontent.com/13086747/142466278-20b02be6-388d-425c-a48d-cb3a9cd776c9.png)

**Comment by Timo-Breumelhof** [comment]
You screen print looks like you are not using the CkEditor, but the plain text editor (?).
I tried what you describe but I cannot reproduce it TBH.
See: https://youtu.be/ulE3efArYw4

**Comment by JanDr2** [comment]
The editor has been suspicious to me as well since it indeed does not look like CKEditor. However, this "plain text editor" appeared right after installing the module without any further configuration. What sort of an editor can it be? How to configure the AF module to use CKEditor?

**Comment by Timo-Breumelhof** [comment]
It's setting of the Forum.
You need to go into the Forum settings ans select CkEditor by clicking the 3 dots on the Right.
![image](https://user-images.githubusercontent.com/8999382/142659940-55803a50-3119-4f22-be6a-05481269f026.png)

**Comment by JanDr2** [comment]
I found the setting, turning on the HTML Input indeed fixed this issue. Thank you very much, I'm closing this issue now.

**Comment by Timo-Breumelhof** [comment]
ok thank you for the feedback.
I do think that the module could use CkEditor as the default, so you don't have top go into the settings

**Comment by WillStrohl** [comment]
That definitely should be the default and it should be done without worrying about upgrade vs. new install.  That's the default editor in DNN, so it should be the default editor in the forum too.  This would be the best UX for non-technical people.  We can put a comment about it in the release notes.

**Comment by JanDr2** [comment]
Agreed, the default should be the CKEditor, because the "plain text" editor just causes confusion. It's probably the best to just inherit the default editor set in DNN, whatever it may be.

**Comment by WillStrohl** [comment]
Well, the plain text editor does have its use cases.  It just shouldn't be the default.  :)

**Comment by Timo-Breumelhof** [comment]
FYI: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/108
