### ISSUE TITLE
DNN Default Editor not used by default for HTML

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#108]
After setting a Forum to allow HTML, the default editor is "textbox"
This is weird as you just allowed HTML.
The default selection should be the "Default DNN Editor" as there's no real use case for "Textbox" when allowing HTML

![image](https://user-images.githubusercontent.com/8999382/143243438-1b49b9f0-c9a2-4706-92da-48eca50ade9a.png)

## Describe the solution you'd like
Make sure "Default DNN Editor" is the default selection

## Describe alternatives you've considered
none

**Comment by johnhenley** [comment]
Timo, 
There are two options here:
- update the default from text box to HTML editor, but this may not update existing settings for forums/forum groups that previously had it set to textbox and had HTML turned off. 
- capture the 'allow HTML' setting is enabled, and switch the editor setting to HTML editor...
Are you asking for both? I can probably do this one ...

**Comment by johnhenley** [comment]
also, should default change for 'mobile users' as well? I think so, given ability of today's devices...but would like input.

**Comment by WillStrohl** [comment]
It looks like there is still work to do on this one, right?

**Comment by johnhenley** [comment]
Yes awaiting feedback before making any changes.

**Comment by Timo-Breumelhof** [comment]
> also, should default change for 'mobile users' as well? I think so, given ability of today's devices...but would like input.

Yes agreed

**Comment by Timo-Breumelhof** [comment]
> Timo, There are two options here:
> 
>     * update the default from text box to HTML editor, but this may not update existing settings for forums/forum groups that previously had it set to textbox and had HTML turned off.
> 
>     * capture the 'allow HTML' setting is enabled, and switch the editor setting to HTML editor...
>       Are you asking for both? I can probably do this one ...

@johnhenley This issue was for a new forum, where you switched to allow HTML.
I suspect that the module has one of the previous HTML editors had coded in code, but I'm not sure.
So I think we should go for your second suggestion?
