### ISSUE TITLE
ENH: Images oversize the post

### ISSUE THREAD

**Issue by warkhos** [DNNCommunity/Dnn.CommunityForums#1105]
## Describe the bug
I recently published a new post and I paste a screenshot for reference, after I hit save and the new thread was created I was able to see the image going over the defined frame borders for the post itself.

## Software Versions
- DNN: the version in DNN Community website
- Module: the version in DNN Community website

## To Reproduce
1. Create a new thread in the forum module
2. Insert an image by using the clipboard memory and don't specify the width and height
3. save the new thread

## Expected behavior
Image should fit the post dimension. 
The link for the post itself: https://dnncommunity.org/forums/using-dnn/themes-containers-templates/i-can39t-save-a-template/

## Screenshots
![image](https://github.com/user-attachments/assets/e1c65b7e-489c-48bb-bb50-8e19be8db91c)

## Error log
Not able to access this information.

## Additional context
Not applicable.

**Comment by Timo-Breumelhof** [comment]
@warkhos thank you for reporting this. This ia on our list :-)
https://github.com/DNNCommunity/Dnn.CommunityForums/issues/982
