### ISSUE TITLE
ENH: Styling for updated security in control panel

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#1115]
@johnhenley Very nice :-) Sure I'll look at it

_Originally posted by @Timo-Breumelhof in https://github.com/DNNCommunity/Dnn.CommunityForums/issues/1108#issuecomment-2415943229_

![image](https://github.com/user-attachments/assets/eaea1cdf-f407-483e-aa98-9ce0a3b7c2ba)

**Comment by Timo-Breumelhof** [comment]
@johnhenley something like this? 
![image](https://github.com/user-attachments/assets/34b0680d-d3fb-4136-941f-6edf09b30e38)

**Comment by johnhenley** [comment]
> @johnhenley something like this? 
yes that's fine. my issue was the three stacked tables didn't align correctly
