### ISSUE TITLE
ENH: Styling review

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#1117]
TopicView 
TopicsView
Forum view 

Updated community-* templates to move markup from code to template. Review and update css, particularly in-line styles.

**Comment by Timo-Breumelhof** [comment]
@johnhenley Working on this I wondered, whats the use of these? Seem redundant?

![image](https://github.com/user-attachments/assets/85d3e78d-db9e-4172-9a62-0238b0b98732)

**Comment by Timo-Breumelhof** [comment]
@johnhenley oh, the little submenu does not work any more ..

**Comment by johnhenley** [comment]
The hyperlink takes you to the top of main topic and the little arrow takes you to latest reply? I always thought it was a little "too cute" myself and just added another layer of complexity and clutter 🤓

**Comment by johnhenley** [comment]
> @johnhenley Working on this I wondered, whats the use of these in Topics View? Seem redundant?
> 
> 
> 
> ![image](https://github.com/user-attachments/assets/85d3e78d-db9e-4172-9a62-0238b0b98732)
> 
> 

The hyperlink takes you to the top of main topic and the little arrow takes you to latest reply? I always thought it was a little "too cute" myself and just added another layer of complexity and clutter.

**Comment by johnhenley** [comment]
> @johnhenley oh, the little submenu does not work any more ..

Are you talking about these?![image](https://github.com/user-attachments/assets/4ae223d5-fe2c-4cbe-a160-ccd72e87b25e)

**Comment by Timo-Breumelhof** [comment]
@johnhenley yes
Hmm, I wonder how many users are going to understand the difference between thread and last reply..
(I mean in a UX way..)

**Comment by Timo-Breumelhof** [comment]
![image](https://github.com/user-attachments/assets/056647ab-1909-419b-9b35-74d45aae4921)

**Comment by Timo-Breumelhof** [comment]
@johnhenley this is proof of the flexibility of the new templating :-)

`<td class="dcf-col dcf-col-replies">[FORUMTOPIC:LASTREADURL|<a href="{0}" rel="nofollow">[FORUMTOPIC:REPLYCOUNT]</a>]</td>`

**Comment by johnhenley** [comment]
> @johnhenley this is proof of the flexibility of the new templating :-)
> 
> 
> 
> `<td class="dcf-col dcf-col-replies">[FORUMTOPIC:LASTREADURL|<a href="{0}" rel="nofollow">[FORUMTOPIC:REPLYCOUNT]</a>]</td>`

I thought you'd like that 🤓

**Comment by Timo-Breumelhof** [comment]
@johnhenley FYI:

![image](https://github.com/user-attachments/assets/fcdb68b0-f81f-41ac-96cf-c1fe496252f3)
