### ISSUE TITLE
Portal alias with port # not working with Forum ReWriter (friendly URLs)

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#115]
## Describe the bug
Portal alias with port # not working with Forum ReWriter (friendly URLs)

## Software Versions
- DNN: 09.04.00-09.09.xx
- Module: 06.06.00

## To Reproduce
1. Create portal alias with port number, e.g. localhost:81
2. Ensure Forums Friendly URLs are enabled
3. will see incomplete HTML on portal pages (even non-Forums pages)

## Expected behavior
Correct HTML on portal pages (even non-Forums pages)

## Screenshots

![image](https://user-images.githubusercontent.com/9553126/152611720-77de1273-85f8-4b29-8082-0629fed78614.png)

## Error log
Screenshot showing code location where portal alias port number not used. 
Will update code:
- if PortalAliasInfo == null try accessing PortalAliasInfo with a port number
- if null PortalAliasInfo returned after both DNN API calls, just return as no rewrite will occur
- Also will clean up some additional code:
- add ".axd" & "/api/" (e.g. personabar) to excluded url paths 
- additional exclusions (.doc/.docx, .xls/.xlsx, etc.)
- move exclusions earlier in method, since they don't need to go through some of the code if they are excluded.
- remove redundant exclusion checking

![image](https://user-images.githubusercontent.com/9553126/152611745-3d617cbe-710d-4a98-b076-2f45314c297d.png)

**Comment by johnhenley** [comment]
I have code to fix this, pending creating a pull request.

**Comment by Timo-Breumelhof** [comment]
Cool thanks
