### ISSUE TITLE
BUG: URL for just Forum Group should only display that group

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#1152]
## Describe the bug
When you click on a link in the breadcrumb or use a URL directly for a specific forum group, only that group should display.

## Software Versions
- DNN: 09.13.03
- Module: 08.01.20

## To Reproduce
1. https://dnncommunity.org/forums/Getting-Started/
2. You should only see the "Getting Started" forums, but you see more...
![image](https://github.com/user-attachments/assets/d25e3fb5-5686-4e80-a4b0-3f17f9978663)

**Comment by WillStrohl** [comment]
I just tagged this for the 8.2 milestone. 😉
