### ISSUE TITLE
BUG: Error when using What's New 

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#1190]
## Describe the bug
I built and installed 08.02.00 and when I have the What's new module on the page, I get this error:

![image](https://github.com/user-attachments/assets/8acf8b9c-edc1-4922-ad88-5ae9e36a5cdf)

If I delete the module, the Forum works (I have both on one page)

## Software Versions
- DNN: 09.13.03
- Module: 08.02.00 Alpha

## To Reproduce
1. Place both the forum and Whats new on one page
2. Install the current 08.02.00 build
3. See the error

## Error log
Nothing in the DNN Admin log nor in Log4Net

## Additional context
I'm using Xcillion theme on the page

**Comment by johnhenley** [comment]
@Timo-Breumelhof I noticed the same thing last night and have a fix I will put in a separate PR today.
