### ISSUE TITLE
Expand 'hit target' for clicking on sections (attachments/polls/additional options) when editing a topic

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#125]
## Is your feature request related to a problem?
Very tedious to click on a heading in the options when editing a topic.

## Describe the solution you'd like
expand 'hit target' to entire header, not just right side
 
![image](https://user-images.githubusercontent.com/9553126/154337802-ca8443a8-d5f6-4b87-93c9-326703424660.png)

**Comment by Timo-Breumelhof** [comment]
Nice :-)

**Comment by WillStrohl** [comment]
Excellent contribution... Thank you!  :)
