### ISSUE TITLE
Incorrect Dashboard data when AF install multiple times

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#128]
## Describe the bug
When AF is installed on multiple tabs, control panel statistics are incorrect. In particular, when installed fresh on a portal that already has AF installed on another tab, statistics are included from other install(s).
This might be rare, but it was encountered in testing.

## Software Versions
- DNN: 09.04.00
- Module: 06.06.00

## To Reproduce
1. Install AF twice on different modules/tabs
2. View control panel and review statistics

## Expected behavior
Correct statistics, filtered by both portal and module

## Screenshots

This is control panel on a fresh install on a portal that has AF installed on a different tab:
![image](https://user-images.githubusercontent.com/9553126/154727190-ebf728b1-7dcd-4bd8-a2b4-ce924d0c7215.png)

**Comment by johnhenley** [comment]
After review, data in activeforums_UserProfiles is not module-specific, so no way to separate module-specific users.

**Comment by Timo-Breumelhof** [comment]
Oh OK it's not? I didn't know that.

**Comment by johnhenley** [comment]
> Oh OK it's not? I didn't know that.

at least it's portal-specific :)

**Comment by Timo-Breumelhof** [comment]
he he, that's something ;-)

**Comment by WillStrohl** [comment]
Wow... Nice catch!
