### ISSUE TITLE
Vanity Name Ignored for Custom URL

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityForums#13]
Related to this original Issue:  https://github.com/ActiveForums/ActiveForums/issues/342

**Steps to Reproduce**

1. Install and configure the forums with defaults.  
2. Change the Vanity Name for any forum or forum group.  
3. Navigate to the forum or forum group.  

**Expected Behavior**  
The URL in the browser should include the vanity name appended to the URL.  

**Actual Behavior**  
The URL is unchanged and not search- or user-friendly.  

FYI - @johnhenley :)

**Comment by johnhenley** [comment]
The issue I had encountered a long time ago is that the pager control didn’t construct correct URLs when a topic and replies spanned multiple pages (the vanity name for forum group and forum are missing from the URL after first page).  You have to be using vanity / friendly URLs, and you have two (page size) settings (one in module settings and then a per-user override). If you have a page size of 5, and there are 10 replies, the URLs generated for page 2 and 3 URLs are missing the vanity parts of the URL. If you look at the change I made in rewriter.cs it looks at each element – topic / forum / forumgroup when building the URL; previously it only looked at one element. It needed to look at each one independently.

**Comment by johnhenley** [comment]
I have code to fix this, pending creating a pull request.
