### ISSUE TITLE
Getting Started Step Skipped on Sites Without a Profile Page

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#142]
BEGIN EDIT BY WILL STROHL

Steps to Reproduce (as noted in a comment by @vmasanas below):  
- DNN 9.10.2 (not tried on any other)
- Install latest version of forum as usual
- On DNN Site Settings > Site Behaviour > User Profile Page > Select "None specified"
- Create a new page
- Drop the forums module on the page
- You will get the user configuration settings page and not be able to get to the default forums view

END EDIT BY WILL STROHL

I just installed the new 7 RC on a DNN 9.10.2 and the only thing I see on the page is a control to configure the forum seems.
![image](https://user-images.githubusercontent.com/4357679/187462099-98fe8759-62c2-4f80-8040-4350fb66bd73.png)

I've already created some forums and given some permissions. What am I missing here?

**Comment by WillStrohl** [comment]
This is interesting feedback.  I haven't seen this myself yet.  Hey @Timo-Breumelhof & @johnhenley ...  Have you run into this yet?

**Comment by johnhenley** [comment]
It looks like you clicked on the 'my settings' button/link.
![image](https://user-images.githubusercontent.com/9553126/187479276-4334e3fc-b0b3-4465-8263-08bf3b82f8c9.png)

If you click on the 'save' button/link, does it display the forums?

**Comment by vmasanas** [comment]
@johnhenley I've not yet seen this button. I just dropped the forums module on the page, and this is all I get

**Comment by johnhenley** [comment]
In your initial posting, you said:
> I've already created some forums and given some permissions. What am I missing here?
It sounds like you installed the module, put it on a page, and then added some forums.
Are you now trying to put the module on a different page?

**Comment by vmasanas** [comment]
I put the module on a page and only see what I post above.
But I see there's a module action menu that allows me to go to "Control Panel". I went there, I created a group and a forum but when I "exit" the control panel I go back to the same page with nothing more than the image I posted before.

**Comment by WillStrohl** [comment]
Yeah, I think there needs to be a new "Steps to Reproduce" added. I just tried to add the v7 module to a page on a clean installation of DNN Platform 9.10.02, and it installed and added to the page as I expected.

**Comment by WillStrohl** [comment]
![image](https://user-images.githubusercontent.com/938023/187485450-d54ef67c-c88f-486e-8dcd-63c5708d9841.png)

**Comment by johnhenley** [comment]
Did you click on the 'continue' button, or did you just click on the 'control panel' link?

**Comment by vmasanas** [comment]
I've never seen any "Continue" button at all

**Comment by vmasanas** [comment]
My site has 3 languages enabled, does this make any difference?

**Comment by WillStrohl** [comment]
Regardless to whether I've chosen to continue or not, the example forums are added, and the navigate appears to be what has always been there.  It's just not intuitive on how to return to the main view if you choose the My Settings view.  Going back to the main forum page like we normally do seems to do the trick.

**Comment by WillStrohl** [comment]
I don't think there is an issue to resolve here unless we can have very clear and reproducible steps that we can use to troubleshoot a specific issue.  Sorry, @vmasanas .  :(

**Comment by vmasanas** [comment]
I'm downloading a backup without the module installed and will repeat this on my local pc and reply back in a few minutes

**Comment by vmasanas** [comment]
And done, and same result. Restored a backup from this clean DNN 9.10.2, installed the module, dropped the module on a page and same thing. No forums at all!

**Comment by WillStrohl** [comment]
Yeah... That's great that you can reproduce this, @vmasanas , but we need to also be able to reproduce it if we're to help with any potential resolution.  Sorry.  :(

**Comment by vmasanas** [comment]
I did a full new installation and doesn't happen there, so not sure what's wrong on the other one. The only thing I remember doing there is customizing the user profiles so I have some very specify properties and deleted most of the ones I don't need.
@WillStrohl  would a full backup of this environment help you with this? I can provide it if you want. Just let me know how/where you want if and you'll have it.

**Comment by johnhenley** [comment]
> And done, and same result. Restored a backup from this clean DNN 9.10.2, installed the module, dropped the module on a page and same thing. No forums at all!
> 
> 

Did you see the continue button and if so, did you click it?

**Comment by johnhenley** [comment]
> I did a full new installation and doesn't happen there, so not sure what's wrong on the other one. 
Did you see the 'continue' link in this new install?

**Comment by vmasanas** [comment]
John I have now two installations with different results
- clean DNN with 3 languages, no other changes: all working ok.  I saw the continue button and all is perfect

- clean DNN with 3 languages, and profiles highly customized: not working (not sure this is the issue but this is the only thing I can think of right now that's different between the two.  Here I never saw the continue button.
-

**Comment by WillStrohl** [comment]
Okay. If we can somehow figure out how to consistently determine and maybe even fix the conflict with the profile customizations, that might be something we'll need to include in a future release - or document for everyone to know to avoid.  Other than that, I think the rest is working as expected.  Right?

**Comment by johnhenley** [comment]
@WillStrohl I have reviewed the code that handles the install and initialization. If the 'continue' button is never clicked, this would result in the page displaying as @vmasana is experiencing. 

@vmasanas on the site where it is not working, please go to the module settings where you installed the forums module, and post a screenshot of the module permissions tab.

**Comment by johnhenley** [comment]
@vmasanas Also, when you install and say you don't see the continue button, do you see the rest of this page?

> ![image](https://user-images.githubusercontent.com/938023/187485450-d54ef67c-c88f-486e-8dcd-63c5708d9841.png)

**Comment by vmasanas** [comment]
@johnhenley see permissions:
![image](https://user-images.githubusercontent.com/4357679/187506874-c561e7f3-6325-482f-9b9a-561338a2c49a.png)


and no, on the site where it does NOT work I never saw the view you posted. On the site where it works I saw that and all is ok there.

**Comment by johnhenley** [comment]
Do your users have the following properties:
DisplayName, FirstName, LastName, PreferredTimeZone, PreferredLocale
Can you send a FULL screen shot of the user profile properties for the site.
Site Settings | Site Behavior | User Profiles 
should look like this:

![image](https://user-images.githubusercontent.com/9553126/187513454-c8b33c5d-9eea-4f7c-a42f-6e23913abf6e.png)

**Comment by johnhenley** [comment]
Also, just for completeness, can you check the DNN admin logs foe when you installed the forums module to see if any errors occurred?

**Comment by vmasanas** [comment]
John the properties you mention are there and no errors on the event log. BTW, notice that I mentioned the point with the user profile just because it's the only thing I remember changing there. It might have nothing to do with the issue I'm facing.

**Comment by vmasanas** [comment]
Ok I think I finally found what the problem was. Go to Site Settings > Site Behaviour and under User Profile Page select "None specified". I can consistently reproduce my issue by enabling or disabling the profile page.

**Comment by johnhenley** [comment]
@vmasanas Glad you found the root cause. Does having this setting to a specific page cause any problems with your site? 

@WillStrohl I'm guessing this is not a regression for this release but has probably worked that way all along. Do you want to update the issue title to include this key info and mark it as a bug?

**Comment by WillStrohl** [comment]
Let's mark this as a new bug and update the title, yes.  Thank you everyone for helping track down this root cause.  :)

**Comment by WillStrohl** [comment]
@vmasanas Would you mind please updating your original post to include a more accurate description and steps to reproduce?  Thank you in advance for your help! :)

**Comment by vmasanas** [comment]
How to reproduce:

- DNN 9.10.2 (not tried on any other)
- Install latest version of forum as usual
- On DNN Site Settings > Site Behaviour > User Profile Page > Select "None specified"
- Create a new page
- Drop the forums module on the page
- You will get the user configuration settings page and not be able to get to the default forums view

**Comment by WillStrohl** [comment]
> How to reproduce:
> 
> * DNN 9.10.2 (not tried on any other)
> * Install latest version of forum as usual
> * On DNN Site Settings > Site Behaviour > User Profile Page > Select "None specified"
> * Create a new page
> * Drop the forums module on the page
> * You will get the user configuration settings page and not be able to get to the default forums view

I've updated the description for you.

**Comment by WillStrohl** [comment]
Since @johnhenley was kind enough to dig into this and provide a fix right away, we'll include it into the current pending release and issue a new RC for review by the community.  

CC: @Timo-Breumelhof, @vmasanas
