### ISSUE TITLE
How to create a theme for the forums

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#143]
Is there any documentation on how to create a theme for the forums? Or sharing the theme available at https://dnncommunity.org/forums so we can start by customizing it?

**Comment by WillStrohl** [comment]
There isn't any formal or current documentation for this module.  We'd welcome anyone that wishes to help create and maintain documentation with us.  

The theme is mostly template-based and the template changes you make are stored in the database.  Outside of that, you'll want to maintain any CSS-related updates in your actual website theme.

**Comment by vmasanas** [comment]
thanks @Timo-Breumelhof  will take a look. I see the theme that's on DNNcommunity website is quite nice, maybe it would be helpful to share this as a sample.

**Comment by Timo-Breumelhof** [comment]
there's a link to a download for that in issue #92 :-)

**Comment by WillStrohl** [comment]
Maybe the community theme can become the default forum theme once the way the theme is saved is updated.

**Comment by WillStrohl** [comment]
Since this is only help/question...  Can we close this issue at this point?
