### ISSUE TITLE
DNN Incremental Search not working in certain situations

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#148]
## Describe the bug
DNN Search is not populating correctly from Active Forums in certain situations:

## Software Versions
- DNN: 09.04.00
- Module: 07.00.00

## To Reproduce
1. In module settings, set delete behavior to 'remove content immediately', and re-index content; no content will be (initially) indexed but subsequent content may or may not be indexed, depending on next setting.
2. if _not_ using friendly URLs, links are not generated and content is not indexed.

## Expected behavior
Search results will be populated during initial and incremental content indexing.

**Comment by WillStrohl** [comment]
Hey @johnhenley ...  Did you mean to make changes to the default template? 😃

**Comment by johnhenley** [comment]
I _thought_ I created a new issue as a placeholder but haven't filled in details yet?

**Comment by WillStrohl** [comment]
Ah!  :)
