### ISSUE TITLE
Copy All Moderator Features to Both Views

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityForums#153]
## Is your feature request related to a problem?
When moderating a forum, sometimes you need to perform certain tasks, such as locking a topic to prevent further responses.  While you're in the forum thread, you're not able to do this.  Those options are not available.  You have to navigate back to the main forum view, find the post, and then perform the administrative action there.  Such a thing is not productive and difficult at best, but it's also impossible on more active websites where several new posts might be created in the time that this post was last updated, making it difficult to find to moderate.  

## Describe the solution you'd like
All moderator options should be available in the post link in the forum thread listing, as well as while viewing the forum thread itself.  

## Describe alternatives you've considered
None yet.  

## Additional context
None at this time.

**Comment by johnhenley** [comment]
Is this what you mean?
![image](https://user-images.githubusercontent.com/9553126/219448486-7b332b8b-3761-4436-be22-f04c4ecb5751.png)

**Comment by johnhenley** [comment]
or do you mean add them here?
![image](https://user-images.githubusercontent.com/9553126/219452976-311c464e-7243-40af-8f8e-e52751d1faba.png)
