### ISSUE TITLE
Review module cache settings

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#155]
"But I do think we need some kind of debug mode in the module too as clearing the DNN cache for every template change kind of sucks.."

Template developer should be able to disable caching in module settings in order to test template changes.

**Comment by Timo-Breumelhof** [comment]
Great :-)

**Comment by WillStrohl** [comment]
Nice one... Thanks for splitting this one out on its own.  :)
