### ISSUE TITLE
ENH: Ban User

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityForums#165]
## Is your feature request related to a problem?  
Spam is a major problem for any website that allows user-contributed content, such as what the DNN Community does overall, and what this module does all of the time.  Spam comes in many forms, including people that just post things they're not supposed to in order to generate traffic, solicit for sales, and other nefarious things.  

There is also the true moderation concern.  What if a person is being abusive in your community?  How do you prevent them from continuing to abuse others in your community?  

## Describe the solution you'd like  
We need a feature that some other forum solutions have, allowing you to ban a user account from posting in the forums.  This feature  would need to be fully flushed out to determine the data points that should and shouldn't be used to perform the ban.  They may include `Username`, `Display Name`, `Email Address`, and `IP Address`.  Others may be necessary too.  

This information should be used to allow a moderator to perform two specific tasks:  

1. Ban the user from being able to interact with the forums.  They should essentially be read-only for this user.  
2. Have an optional setting that allows the moderator to delete all of the end-user's content up to that point.  While this seems overly destructive at first, this is useful for use cases where they might go on a spree and might have several spam and/or harassment posts.  
3. Have an option setting that allows the moderator to also unauthorize the user.  

### Backend Expectations  
When banning a user account, the IP addresses that were logged for the account should all be added to a ban list via [the login IP filter](https://dnnsupport.dnnsoftware.com/hc/en-us/articles/360005220893), using the DNN API, of course.  

Deleted content should be a permanent action and not a soft delete.  (This would require a very obvious warning message for moderators.)  

## Describe alternatives you've considered  
There is another issue that might mitigate the need for the spam purpose, but this feature would still be useful for abusers in a community.  

[Related Issue 109](https://github.com/DNNCommunity/Dnn.CommunityForums/issues/109)  

## Additional context  
None at this time.

**Comment by Timo-Breumelhof** [comment]
I also wonder is we should add an option for moderators to unauthenticate a user?

**Comment by WillStrohl** [comment]
I like it. I'll add it to the main description so it can be seen together.
