### ISSUE TITLE
Remove AddThis

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityForums#167]
## Is your feature request related to a problem?
There is a feature that allows end-users to optionally choose to share the page using a third-party tool called [AddThis](https://www.addthis.com/).  The intent of such a feature is great, but this probably shouldn't have ever been added as a feature in this module.  

There are too many ways to implement the addition of a content-sharing feature like this.  Including what should be the correct (best practice) way in this case - adding it to the theme and/or creating a theme object that is added to the theme.  

Regardless, the module shouldn't be doing this and it usually should be done at the page-level.  

## Describe the solution you'd like  
Unless we can find a valid use case to do otherwise...  We should remove this feature entirely, including all API, UI, and schema that supports it.  

## Describe alternatives you've considered
None at this time.  

## Additional context
If implemented, this may be a breaking change for anyone that might be using this feature.  For example, many website owners operate on a "it works so don't touch it" kind of style.  So, they'll upgrade thinking the sharing feature is still there, only to find out it's not any longer.  Now, they'll have to scramble to figure out how to implement AddThis in another way.

**Comment by Timo-Breumelhof** [comment]
Agreed, IMO any kind of tracker should be implemented from the template.
BTW addthis is totally not GDPR compliant.
