### ISSUE TITLE
More specific email notifications

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#169]
## Is your feature request related to a problem?
When you subscribed to a Forum, the email notifications work quite well.
But it would be nice if there would be a difference between a "normal" thread notification and one where I actually participated.
Currently (AFAIK) there's no distinction between an email for a  forum you subscribed to and a thread you subscribed to.

## Describe the solution you'd like
Different email notification for 
A: "New post in Forum: X" 
B: "New response in Thread: x"

## Describe alternatives you've considered
None

## Additional context
Also related to: #158

**Comment by WillStrohl** [comment]
Love this one!  I think we need to prioritize the template engine first, before we work on anything new with email templates.  What do you think?  The template engine could/should use the same code, ideally.  

Also, the user tagging definitely should have a different email template...  

Subject Ideas to help illustrate this for others (just examples of ideas):  

- [Username] mentioned You in [ForumName] [WebsiteName]  
- New Posts have been Added in [ForumName] [WebsiteName]  
- Someone Replied to a Post You're Following in [ForumName] [WebsiteName]  

etc...

**Comment by johnhenley** [comment]
New tokens:

[NEWPOST] inserts text "new post" if not a reply
[NEWREPLY] inserts text "new reply" if a reply

[SUBSCRIBEDTOPIC] "Subscribed Topic"
[SUBSCRIBEDTOPICSUBJECT] "Subscribed Topic {subject}"
[SUBSCRIBEDFORUM] "Subscribed Forum"
[SUBSCRIBEDFORUMNAME] "Subscribed Forum {forumname}"
[YOUARESUBSCRIBEDTO] "to Subscribed Topic {subject}" or "to Subscribed Forum {forumname}" depending on subscription

So....
you can have a subject like
A [NEWPOST][NEWREPLY] has been added to [FORUMNAME]
A [NEWPOST][NEWREPLY] [YOUARESUBSCRIBEDTO] on [WEBSITENAME]

**Comment by Timo-Breumelhof** [comment]
great, thanks :-)

**Comment by johnhenley** [comment]
Not 100% satisfied with results so I am reopening to add a couple more tokens. [POSTEDORREPLIEDTO] will insert [RESX:posted] (posted) on a new post or [RESX:repliedto] (replied to) on a reply. [SUBJECTONSUBSCRIBEDFORUM] will insert subject when you are subscribed to a forum.
