### ISSUE TITLE
Remove legacy ActiveSocial integration

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#173]
DNN Community Forums became part of the DNN ecosystem when Active Modules was acquired by DNN several years ago. At the time, it was called ActiveForums and was licensed by Active Modules along with a companion product, ActiveSocial. After the acquisition, the social components (groups, journals, etc.) were implemented within the DNN platform.

The forums code based was converted from VB to C#, and forked several times before being adopted and folded into the DNN Community and renamed to DNN Community Forums. 

However, there is still a lot of legacy code that exists to support integration with the long-abandoned ActiveSocial. In fact, every time you visit a page containing the Forums module, code checks to see if you have ActiveSocial installed by looking for a DLL. 

Any site with ActiveSocial should have been converted by now to use the social features within DNN platform and no longer should be using an abandoned and unsupported product. 

This issue is a placeholder for removing integration with ActiveSocial.

**Comment by Timo-Breumelhof** [comment]
Ah, so you are saying we are supporting for Both the Core social and Active Social?

**Comment by johnhenley** [comment]
> Ah, so you are saying we are supporting for Both the Core social and Active Social?

Exactly.

**Comment by WillStrohl** [comment]
Yes, at the level this module is used and expected to work, the level of integration with current DNN APIs is technically supporting both.  I cringe a bit whenever I see the term 'Active Social' in the UI and whatnot, only because we're so far beyond that at this point.  Now, we have to explain it, because it doesn't make sense to newer community members.

**Comment by Timo-Breumelhof** [comment]
I would not know why we should support Active Social too TBH.
