### ISSUE TITLE
References Copy Local  issue

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#18]
## Is your feature request related to a problem?
**Please describe.**
When you clone the Repo inside a DNN installation (which is what a lot of people still do), and forget to remove copy local for some of the references your DNN dlls get overwritten and DNN crashes unless you are using the exact same version of DNN as the dlls in the ReferencedAssemblies folder.
TBH I don't see a use case to have copy local switched on..

## Describe the solution you'd like
Set copy local to false for all references

## Describe alternatives you've considered
none

**Comment by Timo-Breumelhof** [comment]
Hmm, even with copy local off some of the dlls get overwritten on build it seems

**Comment by hismightiness** [comment]
This appears to be because certain versions of DNN are using different versions of some of the references by Nuget and Nuget defaults to `CopyLocal` being true.  The solution here is to exclude all known DNN references so that any added reference is included, but known references are not.
