### ISSUE TITLE
See Subscribers for a Forum / Topic

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#185]
## Is your feature request related to a problem?
In a community setting it is very useful to see the number of subscribers and maybe even who subscribed to a Topic or Forum.
This can give a better insight of the range of the posted threads.
AFAIK there currently is no way to see this data?

## Describe the solution you'd like
A. A subscription count for a topic / forum you can use in a template visible for Forum admins? Or maybe even public?
B. A list of subscribed users visible for a Forum Admin

No rush ;-)

**Comment by johnhenley** [comment]
I remember a moderator tools feature in an older version that I think included thing like this. I really miss it on occasion. Not sure but I can look around and see if I can find it in an older version or even documentation so I can refresh my aging memory.

**Comment by Timo-Breumelhof** [comment]
@johnhenley haha ok thanks :-)
