### ISSUE TITLE
Forum Aggregator/What'sNew

### ISSUE THREAD

**Issue by frozendnn** [DNNCommunity/Dnn.CommunityForums#205]
The old ActiveForums modules had this feature. 

The current WhatsNew module collects topics from all designated forums and displays them. In this module we have a choice to show topics only or replies. My issue is with topics only. I dont know how to make sense of it. Please bear with me. 

IN topics only mode this what happens 
Topic 3
Topic 2
Topic 1 

So if I post a reply in Topic 1, Topic 1 should jump to the top to show that this the currently active topic or a reply was posted here. Howeve this dosent happen. I can post thousand replies in topic 1 but it will stay there. So the most active topic gets pushed down by other topic even if they dont have any replies. 

If we disable topics only, then the what'snew is flooded with the replies on one topic so disabling Topics only doesnt make sense. 

re: Topic 1
re: Topic 1
re: Topic 1
Topic 4
re: Topic 1
re: Topic 1
re: Topic 1
re: Topic 1
re: Topic 1
re: Topic 1
Topic 3
re: Topic 1
re: Topic 1
Topic 2
Topic 1

This looks UGLy 

This used to work in old versions of AF but for some reason Will and Co. took it away. Would be great to have it back.

**Comment by Timo-Breumelhof** [comment]
AFAIK we did not remove anything from that module. Does this work the way you describe it on the latest version @ https://github.com/ActiveForums/ActiveForums?

**Comment by frozendnn** [comment]
Sorry for the  misunderstanding. You did not. ActiveModules removed it long time ago.

**Comment by johnhenley** [comment]
@frozendnn I see that the ranking is by date created and really should be using date create *OR* last reply date. Agreed?

**Comment by frozendnn** [comment]
> @frozendnn I see that the ranking is by date created and really should be using date create _OR_ last reply date. Agreed?

Yes sir! Thank you so much!

**Comment by WillStrohl** [comment]
I didn't take anything away from anyone.  😆
