### ISSUE TITLE
ForumViewer

### ISSUE THREAD

**Issue by frozendnn** [DNNCommunity/Dnn.CommunityForums#206]
Old ActiveForum had this module. It was provided separately. 

Scenario: Let's say I only want one Forum. If I am using only one forum the page looks empty. This is when the ForumViewer came in handy. It would take everything from the existing forum and show the TopicsView directly on the page instead of the forum group. Sorta like https://www.dnnsoftware.com/answers or other forums simpleforum or LveForum. It was very neat but it was removed. I am not sure if WIll still has the source code or how difficult it will be to add this to this project. Or maybe someone can do this and start charging? 

I am willing to sponsor this if it remains opensource.

**Comment by Timo-Breumelhof** [comment]
Was this part of the Open Source distribution?

**Comment by frozendnn** [comment]
> Was this part of the Open Source distribution?

It wasnt but ActiveModules provided this module long time ago and they discontinued it. I am just saying that it was there and it can be done and someone should do it and sell it or we can crowd fund it so it stays opensource.

**Comment by johnhenley** [comment]
I do remember using this feature; it's still in the code repository, so let me see what I can do.

**Comment by Timo-Breumelhof** [comment]
Wouldn't it be better to combine the two instead of having two "slave modules"?

**Comment by johnhenley** [comment]
> Wouldn't it be better to combine the two instead of having two "slave modules"?

Not really. They have different functionality and it was pretty quick to revive this module. It was part of the "enterprise" package sold by active modules but was probably inadvertently left out of any repackaging done by groups maintaining the open source versions.

**Comment by Timo-Breumelhof** [comment]
ok

**Comment by WillStrohl** [comment]
> > Wouldn't it be better to combine the two instead of having two "slave modules"?
> 
> Not really. They have different functionality and it was pretty quick to revive this module. It was part of the "enterprise" package sold by active modules but was probably inadvertently left out of any repackaging done by groups maintaining the open source versions.

I agree with John.  Let's get this added back.  I guess we can categorize the missing worker module as a bug to keep it in the next release.  :)
