### ISSUE TITLE
Install not working

### ISSUE THREAD

**Issue by trouble2** [DNNCommunity/Dnn.CommunityForums#23]
## Describe the bug
Just tried to instal the 06.04.00 RC 3 on dnn 9.8.0 but it says some files cannot be found, so I guess the manifest is wrong

**Comment by Timo-Breumelhof** [comment]
I tested the installer too can confirm the issue.

**Comment by Timo-Breumelhof** [comment]
@trouble2 And, thank you for testing and reporting this :-)

**Comment by Timo-Breumelhof** [comment]
There are two issues due to the complete revamp of the build process I think.

A. Missing /bin and /sql base paths in the manifest.
B. The resources file for the "Whatsnew" module is missing

My PR above fixes A, we need to look at how we "fix" B.

**Comment by hismightiness** [comment]
I believe this is resolved at this time, right?

**Comment by Timo-Breumelhof** [comment]
I tested an upgrade and it works now.
