### ISSUE TITLE
BUG: In control panel, unable to move forums / forum groups up/down when forums or groups have been deleted

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#254]
## Software Versions
- DNN: 09.11.01
- Module: 07.00.04

## To Reproduce
1. Create 3 forum groups 1,2,3
2. Delete group 2
3. try to move group 3 up above group 1
4. it will not move

## Expected behavior
groups should move corerctly

## Screenshot of groups 
![image](https://user-images.githubusercontent.com/9553126/221996973-aa9356f2-51f8-4fa9-a311-6ba2c61fc802.png)

**Comment by WillStrohl** [comment]
@johnhenley  This is marked as ready to merge, but it's tagged for 8.0.1.  Should we wait, or include it 8.0?

**Comment by johnhenley** [comment]
> @johnhenley  This is marked as ready to merge, but it's tagged for 8.0.1.  Should we wait, or include it 8.0?  

It's in 8.0.1 because it has a sql update and I didn't want to clobber another PR so I've been putting each PR with a sql update into a unique milestone. If you want to merge it, you will need to merge the sql manually to 8.0.0.

**Comment by johnhenley** [comment]
moved to 08.00.00

**Comment by johnhenley** [comment]
@WillStrohl Pulled forward to 08.00.00
