### ISSUE TITLE
wwwroot directroy size is increasing massively

### ISSUE THREAD

**Issue by adityakanungo05** [DNNCommunity/Dnn.CommunityForums#287]
In Azure web app, wwwroot directroy size is increasing massively. As I mentioned in \site\wwwroot\Install\Temp folder which stores the extension backup is carrying very large size. Is it safe to delete the files in temp folder, will it affect in anyway to my live website?
Please respond as soon as possible.
Thank you.

**Comment by johnhenley** [comment]
Hello @adityakanungo05. This repo is specifically for the forums module. You should probably post your question on the DNN platform repo or on dnncommunity.org.

**Comment by Timo-Breumelhof** [comment]
Closing as Off topic @adityakanungo05 please use the forums for these kind of questions.
I saw you even sent an email to the community email account, that pretty much starts to feel like spam TBH

**Comment by adityakanungo05** [comment]
They blocked me from dnn community forum after just few minutes of registering.
I just want an expert opinion on my issue.
Please unblock me from forum, I just want little help from your side.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Timo-Breumelhof** [comment]
If this is your username "aditya05"
You are not blocked on https://dnncommunity.org/ as a user.
Or do you see a Cloudflare block? Some Networks are blocked due to excessive spam

**Comment by adityakanungo05** [comment]
I think it’s a cloudfare block.
Please find the attached screenshot below: ***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by Timo-Breumelhof** [comment]
I don't see the screen print

**Comment by adityakanungo05** [comment]
***@***.***

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by johnhenley** [comment]
> 
> 
> In Azure web app, wwwroot directroy size is increasing massively. As I mentioned in \site\wwwroot\Install\Temp folder which stores the extension backup is carrying very large size. Is it safe to delete the files in temp folder, will it affect in anyway to my live website?
> 
> Please respond as soon as possible.
> 
> Thank you. 
> 
> 
> 
> 

Please post in https://github.com/dnnsoftware/Dnn.Platform. That is the appropriate repository.
