### ISSUE TITLE
Duplicated 'subscribe' checkboxes in topic view

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#300]
## Is your feature request related to a problem?
Topic view with quick reply shows two subscribe checkboxes, which are not synchronized. 
Investigate if one can be eliminated to remove confusing UI, or synchronize them.
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/a2647760-b1af-4b75-8309-1e448381cfe1)

**Comment by WillStrohl** [comment]
Like mentioned in email previously, I also have not heard anyone complain about this (yet), but it shouldn't need to wait for that.  :)  Thank you for posting it!

**Comment by johnhenley** [comment]
I have this fixed now :) 
![2023-07-05_17-42-36](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/20ea088a-e39c-4b1d-a55f-4d0ea9ad317f)
