### ISSUE TITLE
ENH: Improve quick reply on Mobile

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#305]
## Is your feature request related to a problem?
Currently the Quick reply box does not work very well on mobile..

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/04ebfa1b-83b3-432a-8393-887b4be182d2)

## Describe the solution you'd like
Make sure it's as easy to use as possible on Mobile. :-)

## Additional context
The quick reply editor is wrapped in a table, we should really use div and flexbox here so we can make sure the title is above the text box and the text box is full width..

**Comment by johnhenley** [comment]
Depends on #348

**Comment by Timo-Breumelhof** [comment]
@johnhenley I created a responsive DIV version. One question though, what is the [AF:UI:ANON] token for ?

**Comment by johnhenley** [comment]
> @johnhenley I created a responsive DIV version. One question though, what is the [AF:UI:ANON] token for ?

It inserts/renders a captcha and username textbox for anonymous users if you allow them to reply.

**Comment by Timo-Breumelhof** [comment]
fixed with new Default Theme
