### ISSUE TITLE
Cannot save 24Hr time setting

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#31]
## Describe the bug
Module does not accept 24 Hr time.

## Software Versions
- DNN: 09.07.00
- Module: 06.04.00

## To Reproduce
1. Go to Module settings
2. @ Display Settings > Time Format; insert HH:mm
3. Save Settings
4. Now open the setting again, the value has not been saved

## Expected behavior
Save HH:mm 
And show an error if an invalid value is entered.

& when this field is left empty just use the preference of the portal / user?

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/99691430-85e20380-2a89-11eb-9455-319191400603.png)

## Error log
none

**Comment by Plumifrons** [comment]
What happens if you use HH:mm tt

**Comment by Timo-Breumelhof** [comment]
@Plumifrons hmm that does work. But it's weird that the initial value is hh:mm, while in code it looks like the default is hh:mm tt. Definitely needs validation so you get warned when the value is not accepted..

**Comment by Timo-Breumelhof** [comment]
@Plumifrons 
OK, ik looks like there is a case in-sensitive comparison somewhere.
saving
HH:mm 
after 
hh:mm
has no effect

Saving
HH:mm
after
hh:mm tt
is saved

**Comment by skamphuis** [comment]
Ok, figured this one out. It's in DNN since 8.0.4: Update...Setting stored procedures only store a value when it's different from the current one. But since SQL Server is case insensitive, a change from "hh:mm" to "HH:mm" doesn't get stored.

![image](https://user-images.githubusercontent.com/4275042/99789841-7fa06580-2b23-11eb-8996-f8b1f5bd63bd.png)

I'll make an issue on the DNN Platform project, and after that will make a workaround in the forums.

**Comment by hismightiness** [comment]
Hmmm... I just tried this in a new build and still can't save the setting.  🤔 

Also, this is sadly unrelated to the other issue.

**Comment by Timo-Breumelhof** [comment]
oh..

**Comment by hismightiness** [comment]
Never mind... I misread the steps to reproduce.  This is actually fixed.  The other issue is still unrelated though.  😞

**Comment by hismightiness** [comment]
Fixing this to test another issue... 😛 

![image](https://user-images.githubusercontent.com/938023/99858153-c0a77280-2b41-11eb-85fe-f52fb4c3808b.png)

**Comment by hismightiness** [comment]
FYI - Fixing that revealed a stackoverflow exception because the function was calling itself over and over instead of saving the setting.  I don't know how I missed that in the PR.  😆 

The save was also not using the correct ID per the method name.
