### ISSUE TITLE
Remove HTML <BR> from rendering for distances

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#319]
## Is your feature request related to a problem?
The module is using <br>  element in some places to create vertical space.
That's not the way we do that in 2023 ;-) 
But mainly it's difficult to style using CSS.

As an example, here's the PostInfo template and the rendered HTML next to each other:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/eb4a23dc-5240-436e-887d-1900fd2a3eea)

IMO the module should not insert BREAKS like this.

BTW, I do realize we can only change this for v8 :-)

## Describe the solution you'd like
Make sure the module does not insert breaks for "styling"

## Describe alternatives you've considered
None

**Comment by gnossosp** [comment]
DNN Ver 09.13.03  Forum version 8.0.1
I am having the same issue with ONE forum instance. The error arises in individual Messages where Author block is shown at left.
The problem occurs inside the 
< div class= "dcf-topic-info" >
container.
the rendered code creates a <br> after each closing < /div > tag.

Here is what I have done (without success) to track down the issue.
(after each change I have used a cleared browser on another machine and have cleared server cache and restarted DNN)
I have cleared the theme and replaced with the DNN community theme.
I have installed another forum on another site within this DNN instance. The new site does not exhibit the behavior. 
Module Settings for each forum are identical. 
I have searched the database tables to see if something looks fishy in there, but can not see anything odd.

I would like to solve this myself, but am out of ideas. Any other things I can check/do to  track this one down?
![Screenshot from 2024-06-14 09-07-33](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/72934916/d3e46539-a838-4903-b77d-e770374ca6e5)

**Comment by johnhenley** [comment]
@gnossosp in the control panel, for each instance, compare the profile template that is selected
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/5c1fbffa-e55a-4bdb-be27-c19d036a9c04)

**Comment by gnossosp** [comment]
SOLVED!
Thanks  [johnhenley](https://github.com/johnhenley)

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think this should not be an issue any more with the new templates.
closes #319
