### ISSUE TITLE
BUG: Improve Friendly URL rewriter detection

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#336]
## Describe the bug
The method that detects if the friendly rewriter is installed performs a string search of web.config for the handler name. This leads to false results if the handler is commented out. 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/f7b852a6-610a-427d-afc0-6f741f7fbf50)

## Software Versions
- DNN: 09.11.02
- Module: 07.00.10

## Expected behavior
Properly detect.

**Comment by Timo-Breumelhof** [comment]
haha thanks :-)
