### ISSUE TITLE
Control Panel does not appear when selected from Active Forums Viewer module

### ISSUE THREAD

**Issue by SiteSupportGuy** [DNNCommunity/Dnn.CommunityForums#357]
## Describe the bug
Control Panel does not appear when selected from Active Forums Viewer module. 
It works properly if the Active Forums module has been saved on the same page, but this should not be required.

## Software Versions
- DNN: 9.11.2
- Module: 7.0.11

## To Reproduce
1. Install module
2. Place Active Forums module on a page
3. Place Active Forums Viewer module on another page and set it to one of the default forums from step 2
4. Click on the control panel button
5. Page opens but nothing is on the page

6. Go back and add the Active Forums module from step 2 to this page (not a copy)
7. After the page has saved, remove the Active Forum module you just added
8. Click on the control panel button
9. Page opens with the proper control panel

## Expected behavior
The control panel should open and allow modifications without needing steps 6-9

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/138155760/3173285b-d649-4e2a-944c-46e5d19cbb52)

## Additional context
I have recreated this in a blank dnn install with only the Active Forums installed.

**Comment by johnhenley** [comment]
Hi @SiteSupportGuy. Thanks for reporting this, and I have duplicated it as well. There are some other funky things that don't work from the viewer either, such as the 'users online' feature if you have that configured in the forums module settings on the page where you have the actual forums module installed.

**Comment by johnhenley** [comment]
@SiteSupportGuy The viewer module was originally intended to provide a way to put (perhaps just selected) forums on a different page than the main forums module and really was not expected to be used by administrators. While I understand this being incorrect functionality, I think fixing this should be fairly low priority since and administrator can go to the main forums page to get to the control panel. Do you agree? I don't want you to think I'm being dismissive of your issue so if I'm not understanding, please let me know. Also, we all greatly appreciate you taking the time to report this and for your continued support of the forums module!!

**Comment by SiteSupportGuy** [comment]
Hello @johnhenley, thanks for looking into this. I agree that accessing the control panel from the viewer module is not that important, but our moderation team will certainly come to me asking why it does not work. The Users Online issue you mentioned is a higher priority for me as I have found that it causes error messages to pop up if the page is left open for a long period of time.
Again, thanks for taking the time to look into my report.

**Comment by johnhenley** [comment]
> Hello @johnhenley, thanks for looking into this. I agree that accessing the control panel from the viewer module is not that important, but our moderation team will certainly come to me asking why it does not work. The Users Online issue you mentioned is a higher priority for me as I have found that it causes error messages to pop up if the page is left open for a long period of time.
> 
> Again, thanks for taking the time to look into my report. 

It is fixed here:

https://github.com/DNNCommunity/Dnn.CommunityForums/pull/359
