### ISSUE TITLE
BUG: Opening a forum post from the Viewer module opens the post in the main forum module instead

### ISSUE THREAD

**Issue by SiteSupportGuy** [DNNCommunity/Dnn.CommunityForums#373]
## Describe the bug
Opening a forum post from the Viewer module opens the post in the main forum module instead. This means the user does not stay on the forum page they started in.

## Software Versions
- DNN: 09.11.02
- Module: 07.00.12

## To Reproduce
1. Create a page with the ActiveForums module on it
2. Create another page with the ActiveForums viewer module on it
3. Link the viewer to a forum from the main module
4. Create a post in the viewer module
5. You are now on the main forum page instead of the viewer
6. Go back to the viewer module and click the forum post you just created
7. You are once again on the main page instead

## Expected behavior
The forum post should open in the page it was selected from.

## Additional context
This issue is likely related to the recent fix to the viewer control panel. The fix to the panel has the user open the panel in the main page, which is what also happens to the forum posts.
I tested this locally and on our test site.

**Comment by WillStrohl** [comment]
Thank you for reporting this.  Without testing this use case myself, it definitely sounds like it's related to the recent update you're citing.  

Just so you know, we're not currently planning to release another 7.xx version of the module.  We're now working on v8.0.   Much of the work is already done.  However, this means that you'll need to wait for a major upgrade to receive this fix (should a fix be found and implemented).

**Comment by johnhenley** [comment]
Hi @SiteSupportGuy. I went back and tested this with the previous release (07.00.11) before the control panel change was added, and it works exactly the same way (goes to the main forums page). The viewer module was originally intended to provide a way to place (perhaps just selected) forums on a different page than the main forums module. I'm curious -- can you explain how you are using it where having it jump to a different page is problematic? The same security is still applied to both the viewer and the forums module. Again, I don't want you to think I'm being dismissive of your issue but want to better understand your use case before we attempt to fix. Also, we all greatly appreciate you taking the time to report this and for your continued support of the forums module!!

**Comment by SiteSupportGuy** [comment]
Hello @johnhenley, I just tested 07.00.11 again locally. This version does not cause this issue to happen. When I open a forum post, it stays on the viewer's page and is not redirected.
My goal is to have the main forum module simply be a hub for admin use, while the viewer modules will be used in other parts of the site, linked with their respective topics.

**Comment by johnhenley** [comment]
OK.  Are you using the friendly URLs option with the module?
I just did some more testing and it looks like it works the way you want in 07.00.11 but only if you disable friendly URLs.

07.00.11 -- friendly URL off - works as you want
07.00.11 -- friendly URL on -- goes back to main page
07.00.12 -- both goes back to main page.

**Comment by SiteSupportGuy** [comment]
I am not using it, I do not have the Active Forums URL Handler installed either.
