### ISSUE TITLE
Nothing Appears to Happen When Deleting a Topic w/ No Replies

### ISSUE THREAD

**Issue by WillStrohl** [DNNCommunity/Dnn.CommunityForums#390]
## Describe the bug  
When you come across a forum post that doesn't belong in your community, you might be inclined to delete it immediately.  When you do this in a topic that has multiple replies, it works exactly as you'd expect.  When you do this in a topic that hasn't yet received a reply, it doesn't appear to do what you'd expect.  

## Software Versions
- DNN: 09.12.00
- Module: 07.00.12

## To Reproduce  
1. Clean install of DNN and the forums module.  
2. Add the forums module on a new page, and go through the getting started step.  
3. Go into any forum and create a new topic.  (Probably best to do this as a separate user, but it shouldn't matter.)  
4. Now delete the newly posted topic.  
5. Click the OK button to confirm that you wish to delete the post.  

## Expected behavior  
The post is deleted, as well as the topic since they're the same at this point.  You're redirected to the forum root, or the parent category of that post.  There might even be a success message of some kind.  

In actuality, what should be happening with the current feature set is that you're redirected to the root of the forums module.  

## Actual Behavior  
The post is indeed deleted, but nothing else happens.  You're not redirected.  The message is still in front of you.  The only way you'd know it worked is if you refresh the page, or exit and navigate back the way you originally arrived at the page.  

## Screenshots  
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/938023/c4993c6e-6643-4141-a505-03b570b3d286)

## Error log  
N/A  

## Additional context  
N/A

**Comment by johnhenley** [comment]
@WillStrohl I didn't laugh until I looked at this JavaScript after you delete. We can revamp this when this function gets moved to web api (which should be soon)? 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/47b61990-163d-4bcb-8abc-a950877d0ea5)

**Comment by WillStrohl** [comment]
Oh wow... That's quite a line of code right there!  🤣
