### ISSUE TITLE
Issue re-installing v8

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#408]
## Describe the bug
V8 is still in development, so please close this if it's a non issue.

I built v8 and installed it.
After that I made changes built it again and tried to install over the v8 version.
I get a SQL error in that case.
I guess this is the conversion script?

## Software Versions
- DNN: 09.10.02
- Module: 08.00.00

## To Reproduce
1. install v8
2. install v8 again
3. SQL error 

## Error log
**Note: Debug DLL's**

Failure SQL Execution resulted in following Exceptions: System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Attachments' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Attachments]( [AttachID] [int] IDENTITY(1,1) NOT NULL, [ContentId] [int] NULL, [PostID] [int] NULL, [UserID] [int] NULL, [Filename] [varchar](50) NULL, [DateAdded] [datetime] NULL, [DateUpdated] [datetime] NULL, [FileData] [image] NULL, [ContentType] [nvarchar](50) NULL, [FileSize] [int] NULL, CONSTRAINT [PK_activeforums_Attachments] PRIMARY KEY CLUSTERED ( [AttachID] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_AuditLog' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_AuditLog]( [AuditId] [int] IDENTITY(1,1) NOT NULL, [RelatedId] [int] NOT NULL CONSTRAINT [DF_activeforums_AuditLog_RelatedId] DEFAULT ((0)), [RelatedType] [int] NOT NULL CONSTRAINT [DF_activeforums_AuditLog_RelatedType] DEFAULT ((0)), [UserId] [int] NOT NULL, [AuditAction] [int] NOT NULL, [UserAddress] [nvarchar](50) NULL, [UserAgent] [nvarchar](255) NULL, [DateAdded] [datetime] NOT NULL CONSTRAINT [DF_activeforums_AuditLog_DateAdded] DEFAULT (getdate()), CONSTRAINT [PK_activeforums_AuditLog] PRIMARY KEY CLUSTERED ( [AuditId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Content' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Content]( [ContentId] [int] IDENTITY(1,1) NOT NULL, [Subject] [nvarchar](255) NULL, [Summary] [nvarchar](1000) NULL, [Body] [ntext] NULL, [DateCreated] [datetime] NOT NULL CONSTRAINT [DF_activeforums_Content_DateCreated] DEFAULT (getdate()), [DateUpdated] [datetime] NOT NULL CONSTRAINT [DF_activeforums_Content_DateUpdated] DEFAULT (getdate()), [AuthorId] [int] NOT NULL, [AuthorName] [nvarchar](150) NULL, [IsDeleted] [bit] NOT NULL CONSTRAINT [DF_activeforums_Content_IsDeleted] DEFAULT ((0)), [IPAddress] [nvarchar](50) NOT NULL CONSTRAINT [DF_activeforums_Content_IPAddress] DEFAULT ('0.0.0.0'), CONSTRAINT [PK_activeforums_Content] PRIMARY KEY CLUSTERED ( [ContentId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Filters' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Filters]( [FilterId] [int] IDENTITY(1,1) NOT NULL, [Find] [nvarchar](1000) NULL, [Replace] [nvarchar](1000) NULL, [FilterType] [nvarchar](50) NULL, [PortalId] [int] NULL, [ModuleId] [int] NULL, CONSTRAINT [PK_activeforums_Filters] PRIMARY KEY CLUSTERED ( [FilterId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Forums' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Forums]( [ForumId] [int] IDENTITY(1,1) NOT NULL, [PortalId] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_PortalId] DEFAULT ((0)), [ModuleId] [int] NOT NULL, [ForumGroupId] [int] NOT NULL, [ParentForumId] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_ParentForumId] DEFAULT ((0)), [ForumName] [nvarchar](255) NOT NULL, [ForumDesc] [nvarchar](2000) NULL, [SortOrder] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_SortOrder] DEFAULT ((0)), [Active] [bit] NOT NULL CONSTRAINT [DF_activeforums_Forums_Active] DEFAULT ((1)), [Hidden] [bit] NOT NULL CONSTRAINT [DF_activeforums_Forums_Hidden] DEFAULT ((0)), [TotalTopics] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_TotalTopics] DEFAULT ((0)), [TotalReplies] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_TotalReplies] DEFAULT ((0)), [LastPostId] [int] NOT NULL CONSTRAINT [DF_activeforums_Forums_LastPostId] DEFAULT ((0)), [ForumSettingsKey] [varchar](50) NULL, [ForumSecurityKey] [varchar](50) NULL, [DateCreated] [datetime] NOT NULL CONSTRAINT [DF_activeforums_Forums_DateCreated] DEFAULT (getdate()), [DateUpdated] [datetime] NOT NULL CONSTRAINT [DF_activeforums_Forums_DateUpdated] DEFAULT (getdate()), CONSTRAINT [PK_activeforums_Forums] PRIMARY KEY CLUSTERED ( [ForumId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Forums_Tracking' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Forums_Tracking]( [TrackingId] [int] IDENTITY(1,1) NOT NULL, [ModuleId] [int] NOT NULL, [UserId] [int] NOT NULL, [ForumId] [int] NOT NULL, [LastAccessDate] [datetime] NOT NULL CONSTRAINT [DF_activeforums_Forums_Tracking_LastAccessDate] DEFAULT (getdate()), [MaxTopicRead] int NOT NULL CONSTRAINT DF_activeforums_Forums_Tracking_MaxTopicRead DEFAULT 0, [MaxReplyRead] int NOT NULL CONSTRAINT DF_activeforums_Forums_Tracking_MaxReplyRead DEFAULT 0, CONSTRAINT [PK_activeforums_Forums_Tracking] PRIMARY KEY CLUSTERED ( [TrackingId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_ForumTopics' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_ForumTopics]( [ForumId] [int] NOT NULL, [TopicId] [int] NOT NULL, [LastReplyId] [int] NULL ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Groups' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose) at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady) at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite) at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:6,Class:16 CREATE TABLE dbo.[activeforums_Groups]( [ForumGroupId] [int] IDENTITY(1,1) NOT NULL, [ModuleId] [int] NOT NULL, [GroupName] [nvarchar](150) NOT NULL, [SortOrder] [int] NOT NULL CONSTRAINT [DF_activeforums_Groups_SortOrder] DEFAULT ((0)), [Active] [bit] NOT NULL CONSTRAINT [DF_activeforums_Groups_Active] DEFAULT ((1)), [Hidden] [bit] NOT NULL CONSTRAINT [DF_activeforums_Groups_Hidden] DEFAULT ((0)), [GroupSettingsKey] [varchar](50) NOT NULL, [GroupSecurityKey] [varchar](50) NOT NULL, CONSTRAINT [PK_activeforums_Groups] PRIMARY KEY CLUSTERED ( [ForumGroupId] ASC )WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ) System.Data.SqlClient.SqlException (0x80131904): There is already an object named 'activeforums_Poll' in the database. at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction) at 

...................

System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at System.Data.SqlClient.SqlCommand.ExecuteNonQuery() at DotNetNuke.Data.SqlDatabaseConnectionProvider.ExecuteNonQuery(String connectionString, CommandType commandType, Int32 commandTimeout, String query) at DotNetNuke.Data.SqlDataProvider.ExecuteScriptInternal(String connectionString, String script, Int32 timeoutSec) ClientConnectionId:e2548e30-f5b0-4e9b-824e-afe100b049e8 Error Number:2714,State:3,Class:16 CREATE PROCEDURE dbo.activeforums_Mod_Reject @PortalId int, @ModuleId int, @UserId int, @ForumId int, @TopicId int, @ReplyId int, @Reason int = 0, @Comment nvarchar(2000) AS BEGIN SET NOCOUNT ON; If @ReplyId = 0 --Update Topic BEGIN UPDATE dbo.activeforums_Topics SET IsRejected = 1, IsApproved = 0 WHERE TopicId = @TopicId END ELSE BEGIN UPDATE dbo.activeforums_Replies SET IsRejected = 1, IsApproved = 0 Where TopicId = @TopicId AND ReplyId = @ReplyId END END 

Paste the error log that is related to this issue.

**Comment by johnhenley** [comment]
@Timo-Breumelhof The current dev branch still has some logic in it that does not properly handle reinstall or upgrades in my testing. We had originally attempted to rename the module as part of an upgrade but that messed up future reinstall and upgrades so we abandoned that approach and are just updating the user-facing/"friendly". I have an outstanding PR #394 with an update that still needs to be merged. I tested that version (which removed updates to module naming) with reinstall and upgrading to 8.0.1 and didn't have any issues. So let's test again after that PR gets merged.

**Comment by Timo-Breumelhof** [comment]
@johnhenley ok cool thanks :-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley oh, I now see that I introduced some conflicts by merging the updated icons in the manifest..

**Comment by Timo-Breumelhof** [comment]
Not an issue in latest build
