### ISSUE TITLE
Change FontAwesome CDN to Bootstrap CDN

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#413]
## Is your feature request related to a problem?
**Please describe.**
Change FontAwesome CDN to Bootstrap CDN

## Describe the solution you'd like
Change FontAwesome CDN to Bootstrap CDN

## Describe alternatives you've considered
none

## Additional context
 see https://github.com/DNNCommunity/Dnn.CommunityForums/issues/410.

**Comment by johnhenley** [comment]
note: this ended up being superseded by Forums loading a local copy of FontAwesome
