### ISSUE TITLE
BUG: Multiple emails if subscribed to both forum and topic

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#419]
## Describe the bug
If you are subscribed to a forum and to a particular topic, you receive emails for each. In this case, only the topic subscription should be processed. 

## Software Versions
- DNN: 09.12.00
- Module: 07.00.12

## To Reproduce
1. As user 1, subscribe to a forum and to a topic in that forum. 
2. As user 2, post to that topic. 
3. User 1 will receive two notifications. 

## Expected behavior
Topic subscription should take precedence and forum subscription should be ignored. 

## Additional context
Issue introduced in 07.00.05? #207

**Comment by will** [comment]
@johnhenley I trust your opinion on this. If it's not critical then just whenever.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I guess you meant another @WillStrohl

**Comment by WillStrohl** [comment]
> @WillStrohl do you want this to go into 8.0? Or hold until later? It's not critical imho.

Let's wait until later.  We have a big plate on our table already.  🤙🏽

**Comment by WillStrohl** [comment]
Yeah, later would be better, I think.  But, I've noticed this myself and didn't realize why it was happening.  I thought it was because I was also an Admin or something.

**Comment by johnhenley** [comment]
> Yeah, later would be better, I think. But, I've noticed this myself and didn't realize why it was happening. I thought it was because I was also an Admin or something.

@WillStrohl can we do it with 08.0.0.00 as @Timo-Breumelhof said this is only opportunity to get testers :)

**Comment by WillStrohl** [comment]
When I sent that comment, I didn't realize there was already a PR.  All good!  😊
