### ISSUE TITLE
ENH: New Default filters for quick access

### ISSUE THREAD

**Issue by warkhos** [DNNCommunity/Dnn.CommunityForums#420]
I've been using the Forums module for quite some time now and I believe that including a couple more filters at the top of the module will help reduce time searching. My suggestions are the following:

1. Top 10 messages or replies with most reactions (the "Thumbs up") labeled as "Most Popular Replies"
2. Top 10 subjects with high amount of responses labeled as "Hot Topics"

I visualize these new default filters right next to "Not Read" and ""Unanswered" at the top of the module.

"Most Popular Replies" could help users find the answers from the community with highest thumbs up which could means that those answers are the fix for a top issue everybody is asking; also, this will encourage people to use the "Thumbs up" button.

"Hot Topics" could help users to find the most active conversations right now and allow community members to jump into a conversation where everybody is helping out.

P.D. This is my first Issue on GitHub so I apologize in advanced for any mistake or missing information. :-)

**Comment by WillStrohl** [comment]
Thank you for taking the time to suggest a new feature.  

The information we generally need would be in the Issue template that you deleted to write your suggestion.  🤣 

Anyhow, I think we still have what we need right now.  In the future, please know that the templates for the various types of issues are really helpful to the rest of us who might end up doing the work.  It's best to leave them in place and just replace the bits that are prompting you.  

Regardless, I really love this suggestion!  We're quite bogged with getting ready for the 8.0 release, but I hope we can add something like this shortly after that.

**Comment by johnhenley** [comment]
@warkhos thank you for the suggestion for the new filter features. Should be fairly straightforward to implement so hopefully we can get it into a release soon!

**Comment by warkhos** [comment]
My bad @WillStrohl :-( jeje... It won't happen again.

**Comment by warkhos** [comment]
Thanks for such a quick response @johnhenley!

**Comment by WillStrohl** [comment]
> My bad @WillStrohl :-( jeje... It won't happen again.

No worries. We're all here trying to make something happen.  You're all good!  🤙🏽

**Comment by warkhos** [comment]
Hi @johnhenley! thanks for the follow-up

I believe a good way to do the "likes" could be parametrized this filter based on the dates from each topic in the forum; for example, look at the "most likes" posts from last 6 months/3 months/last year/etc.  

Hope this helps.

**Comment by johnhenley** [comment]
> Hi @johnhenley! thanks for the follow-up
> 
> I believe a good way to do the "likes" could be parameterize this filter based on the dates from each topic in the forum; for example, look at the "most likes" posts from last 6 months/3 months/last year/etc.
> 
> Hope this helps.

Thanks @warkhos I used the last reply date (or create date of the post if no replies) as the filter. PR is done, and it is slated for 08.00.04 release.
