### ISSUE TITLE
BUG: Paging not working

### ISSUE THREAD

**Issue by leedavi** [DNNCommunity/Dnn.CommunityForums#425]
## Describe the bug
On the forum the paging is not working.  Clicking on page 2 will return you to the root forum.

https://dnncommunity.org/forums/aft/4714

## Software Versions
- DNN: 00.00.00
- Module: 00.00.00

## To Reproduce
1. goto forum
2. Click page 2

## Expected behavior
goto page 2

## Additional context

Other forums work, it's just the one listed above.

https://dnncommunity.org/forums/Getting-Started/new-to-dnn/application-error-in-dnn-site/2/

**Comment by Timo-Breumelhof** [comment]
@johnhenley this is on the community site.
@leedavi thank you for logging this :-)

**Comment by johnhenley** [comment]
@leedavi Sorry for missing the details you posted. @Timo-Breumelhof thanks for setting me straight. 

I do see this on the dnncommunity.org site and will investigate.
