### ISSUE TITLE
BUG: v8 upgrade Topicview template issue

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#445]
## Describe the bug
When I upgrade to v8 it seems all my custom templates are copied correctly fro database to .txt file, but the topicview.txt file does not contain the right HTML

## Software Versions
- DNN: 09.10.02
- Module: 08.00.00

## To Reproduce
1. Add some code to TopicView template on forums version 7
2. Upgrade to v8 of the module
3. The code is not in the TopicView.txt file

## Expected behavior
TopicView.txt should contain the data from the database

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/0becc8e7-015a-42a0-a2d4-07f81c021e1d)

## Additional context
I emailed @johnhenley a video demo

**Comment by johnhenley** [comment]
Duplicated
