### ISSUE TITLE
ENH: Remove text vs html versions of templates

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#450]
## Is your feature request related to a problem?
Community Forums 08.00.00 has substantial improvements for template parsing, caching, and editing (e.g. you can now edit a template directly in the file system rather than using the Forums Control Panel). There used to be a requirement to have an HTML vs a text-only version of each template to support plain-text vs HTML emails. These are no longer used, and all emails are using the HTML template.

## Describe the solution you'd like
Remove the html vs plain-text differences in the templates. Handle existing templates during 08.00.00 upgrade.

**Comment by WillStrohl** [comment]
Nice!

**Comment by johnhenley** [comment]
> Nice!

@WillStrohl it's ready for you :)
