### ISSUE TITLE
ENH: HTML structure > Use Heading instead of span with class 'aftitlelg"

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#457]
## Describe the bug
In 4 places the module uses a span with a class and CSS to make the text larger.
For consistency / styling and accessibility it's better to use a heading as that's what it is

## Software Versions
- DNN: 08.00.00
- Module: 09.10.02

## To Reproduce
1. Search the solution for aftitlelg
2. You will find 4 cases of this <asp:Label ID="lblHeader" CssClass="aftitlelg" runat="server" />

## Expected behavior
Use h1-6 for headings

## Solution
I suggest we wrap the label like this:

`<h3 class="dcf-heading-3"><asp:Label ID="lblHeader" CssClass="aftitlelg" runat="server" /></h3>`

So we keep the old class as a fallback.
This is a subheading inside the module where h3 seems the most appropriate?

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/b2168c0b-41c8-4d91-8d70-52d03124300e)

**Comment by johnhenley** [comment]
Good suggestion. Do you want me to do this?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Sure
