### ISSUE TITLE
ENH: Template extension html/ascx instead of txt?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#460]
## Is your feature request related to a problem?
I'm working on the new community Theme and when editing the template files the .TXT extension means I have to set the document type manually. 

## Describe the solution you'd like
Wouldn't an .htm(l) or .ascx extension be more logical as they are essentially html files..?
.ascx would also offer a bit of for protection? (so those are not "served" to the outside world)

## Describe alternatives you've considered
none

## Additional context
Just a thought..

**Comment by johnhenley** [comment]
I think ascx I good. Let me know if you want me to make the changes and do pull request.

**Comment by Timo-Breumelhof** [comment]
yes please :-)

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof can you please merge PR #456 first since that will avoid merge conflicts?

**Comment by Timo-Breumelhof** [comment]
done

**Comment by johnhenley** [comment]
> done

wow, that was fast :)

**Comment by Timo-Breumelhof** [comment]
Right I mainly wondered if I had to change the email templates too.
Thank you.
BTW, it was funny "my theme broke" after the last update until I realized this was the cause
