### ISSUE TITLE
Legacy theme name on upgrade

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#462]
## Please summarize your question in one sentence
Is it smart to name the legacy Theme "default" after you upgraded?

## Give a more extended description
Should we rename the v7 default theme "legacy" on upgrade?
And name the "new community" one "default"?
Or maybe v8-default?

**Comment by johnhenley** [comment]
I struggled with that as well but didn't want to break anything on an existing install. We can rename to "legacy", which would require updating the module settings during the upgrade, and renaming the folders, both are OK with me. Do we need to be concerned with anyone with references to "default" folder in custom code or templates or CSS or anywhere else?

BTW, I personally prefer "community" to "default".

Will not change anything yet until we have consensus.

**Comment by Timo-Breumelhof** [comment]
I just want to avoid that anyone will think that the template in the "default" folder is the default.. :-)
No problems with "community" TBH.
I think there's a very small chance that anyone will reference the default folder and if they do they can copy it manually :-)
