### ISSUE TITLE
ENH: Change rendering during token replacements e.g.,[FORUMICONCSS]

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#467]
## Is your feature request related to a problem?
**Please describe.**
When I use [FORUMICONCSS] renders this:

`<div style="height:30px;margin-right:10px;"><i class="fa fa-folder fa-blue fa-2x"></i></div>`

I think we should avoid rendering any inline styles like this as they are cumbersome to overrule / restyle and not needed.

## Describe the solution you'd like
Just render 
`<i class="fa fa-folder fa-blue fa-2x"></i> `
if a div is needs it can be inserted in the template

**Comment by johnhenley** [comment]
1) centralize token replacement
2) use a TokenResources.resx to store html snippets
