### ISSUE TITLE
Question: indicate status of a forums using a class

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#468]
## Please summarize your question in one sentence
* I did not check yet, just logging... so it might be that we already have this option..
Should we have a token for a forum / thread status?

## Give a more extended description
Thinking about #467 a bit more.
A forum / Thread has a status for a user.
Like 0 threads, 1+ threads, all read some not read etc.
We now indicate this by rendering another icon.
I think it would be useful if we had a token that renders a state class.
Like 

  dcf-unread 
  dcf-read

etc. (just a suggestion, I guess we can come up with better terms)

That way a theme developer could add a class to the wrapping div and style the whole row and / or overrule the icons we currently use.

**Comment by johnhenley** [comment]
I think we'd want to denote unread topics vs forum with unread topics. New topics and new replies. All probably could have their own classes which theme builders could use to style as desired.

**Comment by Timo-Breumelhof** [comment]
Agreed

**Comment by WillStrohl** [comment]
This is a good one!  😊

**Comment by johnhenley** [comment]
@Timo-Breumelhof I know we have discussed adding "block tokens" like this to include/exclude template sections:

`[WHEN:UNREAD:TOPICS] ... [/WHEN:UNREAD:TOPICS]`

`[WHEN:ALL:TOPICS:READ] ... [/WHEN:ALL:TOPICS:READ]`

`[WHEN:NEW:TOPICS] ... [/WHEN:NEW:TOPICS]`

But for now I want to just get the CSS classes in that you want:

Forums view:

You add a token to template:
<div class="[DCF:FORUM:STATUS]">

This gets replaced with:

- `dcf-forumstatus-no-access` (you have "view" but not "read" access--IMHO we should just remove one)
- `dcf-forumstatus-no-topics` (forum is empty)
- `dcf-forumstatus-new-topics' (last post in forum > user's last read post)
- `dcf-forumstatus-unread-topics` (user has read newer posts but hasn't read every topic)
- `dcf-forumstatus-all-topics-read` (user has read every topic in forum)

Topics view:
<div class="[DCF:TOPIC:STATUS]">

- `dcf-topicstatus-new' (post > user's last read post; user hasn't read at all or may have read original post and earlier replies but there are new replies)
- `dcf-topicstatus-unread` (user hasn't read at all)
- `dcf-topicstatus-read` (user is up-to-date on topic and any replies)
- `dcf-topicstatus-authored` (user is the one who created it) 

This may result in multiple variations such as unread + authored. 

Topic view template: 
<div class="[DCF:POST:STATUS]">

- `dcf-poststatus-new' (post/reply > user's last read post)
- `dcf-poststatus-unread` (user hasn't read)
- `dcf-poststatus-read` 
- `dcf-poststatus-authored` (user is the one who created it)
