### ISSUE TITLE
ENH: Add [FORUMPARENTNAME] token for sub forums

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#469]
## Is your feature request related to a problem?
**Please describe.**
I would like to show the Parent forum name in a template

## Describe the solution you'd like
See:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/b9b205e3-fd0d-404e-82f9-16130315aee0)

It would be nice if one could show the highlighted as:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/e006d5ce-95f5-4226-ad65-0af0c003e9e9)

To communicate more clearly it's a sub-forum of X

## Describe alternatives you've considered
None

**Comment by johnhenley** [comment]
In 8.2, with token [FORUM:PARENTFORUMNAME]
