### ISSUE TITLE
ENH: Custom Localized texts in Templates

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#470]
## Is your feature request related to a problem?
**Please describe.**
It would be nice if one could add ML texts to a template

## Describe the solution you'd like
In this template:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/5de3687e-2fc5-4885-b44b-fe1729e1ad40)

The highlighted texts are now "hard coded".
It would be nice if these where translatable using a resource file?

**Comment by johnhenley** [comment]
[RESX:Group] exists already. Add resources for:
Child
Sub forum
...others?
