### ISSUE TITLE
ENH: What to do with "Collapse"

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#471]
## Please summarize your question in one sentence
The current collapse functionality is difficult to style and looks legacy.

## Give a more extended description
We have the [GROUPCOLLAPSE] token.
Currently that loads an image and renders this:

<img class="afarrow" id="imgGroup2" onclick="toggleGroup('2', 'afarrow', 'afarrow');" src="/DesktopModules/ActiveForums/images//arrows_down.png" alt="Toggle Group Display">

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/b0d5b12a-06d0-4391-b8ff-5f01a1cf598b)

I see two options to improve on this:
- We change that it to a fontawesome icon and add a CSS class for the state. (dcf-open dcf-closed)
That way it looks better and is stylable without a lot of hacks.

- We remove support for this and leave it to the Theme builder you add his own script?

Opinions?

**Comment by Timo-Breumelhof** [comment]
Related to #51

**Comment by johnhenley** [comment]
I vote for option 1

**Comment by johnhenley** [comment]
@Timo-Breumelhof 
There are 4 different uses of this:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/3251dfc9-2258-4b59-a890-953d4f459577)

The toggleGroup sets a cookie, which the toggleSection does not.
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/4284b151-8a22-456a-80d6-975bccf97840)

While we can probably do *something*, should we defer this for now? 
My brain is too tired to try and come up with a good solution, which will require tweaking the html, js, and css...

**Comment by Timo-Breumelhof** [comment]
@johnhenley agreed v9

**Comment by johnhenley** [comment]
> @johnhenley agreed v9

Or hopefully sooner. But not v8

**Comment by johnhenley** [comment]
> @Timo-Breumelhof 
> 
> There are 4 different uses of this:
> 
> ![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/3251dfc9-2258-4b59-a890-953d4f459577)
> 
> 
> 
> The toggleGroup sets a cookie, which the toggleSection does not.
> 
> ![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/4284b151-8a22-456a-80d6-975bccf97840)
> 
> 
> 
> While we can probably do *something*, should we defer this for now? 
> 
> My brain is too tired to try and come up with a good solution, which will require tweaking the html, js, and css...

@Timo-Breumelhof i will take this one. I see it more clearly now. It needs to be refactored and generalized. Have two functions to essentially do the same thing is just lazy :) and the cookies code should be separated out.

**Comment by Timo-Breumelhof** [comment]
Sounds good to me.
How would you target the target element to collapse / expand?
BTW target the target, nice one too ;-)

**Comment by WillStrohl** [comment]
> I vote for option 1

Me too.

**Comment by johnhenley** [comment]
> > @Timo-Breumelhof
> > There are 4 different uses of this:
> > ![image](https://user-images.githubusercontent.com/9553126/269768783-3251dfc9-2258-4b59-a890-953d4f459577.png)
> > The toggleGroup sets a cookie, which the toggleSection does not.
> > ![image](https://user-images.githubusercontent.com/9553126/269768596-4284b151-8a22-456a-80d6-975bccf97840.png)
> > While we can probably do _something_, should we defer this for now?
> > My brain is too tired to try and come up with a good solution, which will require tweaking the html, js, and css...
> 
> @Timo-Breumelhof I can try this one if you want. I see it more clearly now.
> 
> It needs to be refactored and generalized. Having two functions to essentially do the same thing is just lazy :) and the cookies code should be separated out.
> 
> You have a "thing" (a section, a group, quick reply, whatever) that is "collapsible" with an "opened" or "closed" state.
> 
> (As an aside, this is where our English falls flat. "Open" can be used as an adjective or a verb. "Close" is a just verb--or an adjective with an entirely different meaning:) "Closed" is the adjective. So I use "opened" which is clearer as the adjective opposite of "closed".)
> 
> You open or close the "thing" which changes the icon and updates the cookie. Any "thing" that is collapsible deserves a cookie.
> 
> You have a `div` with `` dcf-collapsible`` and either ``dcf-collapsible-opened`or`dcf-collapsible-closed`. Inside the `div` you have the fontawesome icon tag.
> 
> What do you think?

@Timo-Breumelhof BTW, the cookie doesn't really work. If you load a topic, toggle the quick reply, then refresh the browser, the quick reply is visible again :)
