### ISSUE TITLE
ENH: Search template from file?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#473]
## Please summarize your question in one sentence
I'm trying to style the Forum Search, but the used template is not ideal to do that.

## Give a more extended description
I would really like to make changes to it, but that will break existing Themes.
Can we also load this one from a template file?
That would allow changing it and not break existing Themes

## Steps to reproduce (if needed)
see: https://github.com/DNNCommunity/Dnn.CommunityForums/blob/cbf421a0d0be135bccd0e2df6eb84fdcac1e2ed8/Dnn.CommunityForums/class/Utilities.cs#L220

**Comment by johnhenley** [comment]
Can you create a desired template and either attach it here or add it to the project?

**Comment by Timo-Breumelhof** [comment]
@johnhenley I will

**Comment by johnhenley** [comment]
@Timo-Breumelhof i have done this using the template you had hardcoded previously.
