### ISSUE TITLE
ENH: Icon - text combination: wrap text in span

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#474]
## Is your feature request related to a problem?
**Please describe.**
The main forum action links are difficult to align vertically.
This is due to the text not being wrapped inside a span.

Exaggerated example:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/37452cb0-07a7-4660-9e07-4e1105048a31)

## Describe the solution you'd like
Wrap the text in a span so you can use flexbox to align icon and text.
See: https://github.com/DNNCommunity/Dnn.CommunityForums/blob/cbf421a0d0be135bccd0e2df6eb84fdcac1e2ed8/Dnn.CommunityForums/class/Utilities.cs#L189

This should not influence existing Themes

**Comment by johnhenley** [comment]
@Timo-Breumelhof is there a better way to separate via styling the items on the left va the right on the toolbar. I have a couple of more views that are added in this PR #433. In that PR I tweaked the width in the css I think. It's getting crowded so I'm wondering if we need to do a different type of UI control etc.

**Comment by johnhenley** [comment]
@Timo-Breumelhof  does the span need to render a css class, or do you just want these wrapped in span tag?


![Image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/88548b40-ffd9-4c78-b0d1-72ffbf27fe89)

**Comment by johnhenley** [comment]
Should we make this a template? It seems kinda silly that there is a "toolbar" control with a template, and then we also call this "toolbar" but it's not templated :)

**Comment by Timo-Breumelhof** [comment]
> @Timo-Breumelhof does the span need to render a css class, or do you just want these wrapped in span tag?
> 
> ![Image](https://user-images.githubusercontent.com/9553126/269431872-88548b40-ffd9-4c78-b0d1-72ffbf27fe89.png)

I have used this for now on other ones:

`<div class="dcf-icon-text"><i class="fa fa-file-o"></i><span class="dcf-text">Last Post</span></div>`

That's because using span selectors is not very good for performance.

**Comment by Timo-Breumelhof** [comment]
> Should we make this a template? It seems kinda silly that there is a "toolbar" control with a template, and then we also call this "toolbar" but it's not templated :)

Yes, sounds logical. I see a small disadvantage. When there's a new "icon" (functionality) old themes will not  have that. Unless we template the [icon - text] combination..

**Comment by Timo-Breumelhof** [comment]
I decided to use "dcf-link-text" seems better

**Comment by Timo-Breumelhof** [comment]
Closed using #524
