### ISSUE TITLE
BUG: [RESX:Views] is not supported in UPPERCASE

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#475]
## Describe the bug
[RESX:Views] works [RESX:VIEWS] does not.
All other tokens are uppercase..

## Software Versions
- DNN: 09.10.02
- Module: 08.00.00

## To Reproduce
1. Edit the TopicsView template
2. insert both [RESX:VIEWS] and [RESX:Views]
3. [RESX:VIEWS] is not parsed

## Expected behavior
IMO  [TOKENS] should either all be uppercase or case agnostic.

**Comment by johnhenley** [comment]
@Timo-Breumelhof These are resource strings not tokens so I think this is normal DNN/.NET framework behavior?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Hmm probably, but it's weird that some are uppercase and some are not

**Comment by johnhenley** [comment]
@Timo-Breumelhof so are you saying the module's resources are named inconsistently?

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think so?
