### ISSUE TITLE
Add support for [RESX:RATINGS] and [RESX:STATUS]

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#476]
## Is your feature request related to a problem?
**Please describe.**
When rendering Ratings and Status in a columns it would be nice to have a column title that's translatable.

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/19d5c371-f38e-41d3-889a-919ae0a1c19e)

## Describe the solution you'd like
Add  [RESX:RATINGS] and [RESX:STATUS]

**Comment by johnhenley** [comment]
@Timo-Breumelhof [RESX:Status] already exists but nothing for Rating.

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof 

I'm sure I've asked before but do you know why there are a bunch or resources that aren't preceded by RESX: ??

For example 

"[RESX:Lock].Text" 
"Lock.Text"

Should this be an issue?

**Comment by Timo-Breumelhof** [comment]
I don't know but it's not very logical , right?

**Comment by Timo-Breumelhof** [comment]
> @Timo-Breumelhof [RESX:Status] already exists but nothing for Rating.

ok thanks
