### ISSUE TITLE
Wrap Search results in wrapper class

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#480]
## Is your feature request related to a problem?
**Please describe.**
For easier styling it would be good if the filtered / Search results would be wrapped in a  wrapper class.
Now it's difficult to make a distinction between the "af-search-header" div on either Filtered or Search results

I guess 

https://github.com/DNNCommunity/Dnn.CommunityForums/blob/dev/Dnn.CommunityForums/controls/af_search.ascx

is used for Search results 

And 

https://github.com/DNNCommunity/Dnn.CommunityForums/blob/dev/Dnn.CommunityForums/controls/af_grid.ascx

For the filtered list.
But I wonder if this control is also used elsewhere. @johnhenley ?

## Describe the solution you'd like
Add a wrapper div to the ascx with respectively the class

```
dcf-search-results-wrap
dcf-filter-results-wrap
```

**Comment by Timo-Breumelhof** [comment]
@johnhenley hmm, maybe rendering from a template would be a better change..?

**Comment by johnhenley** [comment]
@Timo-Breumelhof i have this covered as part of moving search and filtered results to use templates.
