### ISSUE TITLE
Advanced search Title is not wrapped in an element

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#481]
## Is your feature request related to a problem?
**Please describe.**
All titles seem to follow the standard that the text is wrapped in an element.
In most cases it's a span with a class (instead of an actual heading but that's another issue)
But the one in advanced search is not wrapped at all but in it's parent element.
See:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/1af1b627-74a0-439c-9a07-ac52491eb6e0)

All other titles have this:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/e5a83120-23ac-4f90-af3f-364ba046113f)

## Describe the solution you'd like
Add the same wrapper all other titles use
So `<span class="af-adv-search-title">Topics</span>`

**Comment by Timo-Breumelhof** [comment]
For some reason a literal was used instead of a label (which is good, but not the same as the other titles)
https://github.com/DNNCommunity/Dnn.CommunityForums/blob/cbf421a0d0be135bccd0e2df6eb84fdcac1e2ed8/Dnn.CommunityForums/controls/af_searchadvanced.ascx#L4

**Comment by johnhenley** [comment]
is this what you want?


![Image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/e08cbbe4-705d-4212-a26f-b0a1f83ccc02)
