### ISSUE TITLE
ENH: Conditional rendering

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#486]
## Is your feature request related to a problem?
**Please describe.**
In some cases it's difficult to style items that might be visible or not

## Describe the solution you'd like
In this example, but it would apply to most [TOKENS] that conditionally render content

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/dd8b79ea-46c9-4d2d-9518-ac87d4937780)

There might be a signature but sometimes there is not.

In this case when the signature is absent or empty, the padding of the signature div is still shown.
It would be nice if we could somehow prevent that.
I see two options:

-  Wrap the rendered HTML inside a div with a defined class. If nothing is rendered, the styling does not apply
- Add support for conditional tokens like [HASSIGNATURE] [/HASSIGNATURE]

Suggestions?

**Comment by johnhenley** [comment]
@Timo-Breumelhof does this solve it? 

`.dcf-post-signature:empty {display:none;}`

**Comment by WillStrohl** [comment]
Do we want a more global token that can be used across other tokens as well?  🤔

**Comment by Timo-Breumelhof** [comment]
> @Timo-Breumelhof does this solve it?
> 
> `.dcf-post-signature:empty {display:none;}`

I think it does, but I think some conditions can still be useful

**Comment by johnhenley** [comment]
This should now be accomplished by using the "format" portion of the token. If the token value is empty (e.g. signature), the rest of the markup in the format isn't rendered.
![Image](https://github.com/user-attachments/assets/31968551-2669-4b6d-8c20-f1755e7147c0)
