### ISSUE TITLE
ENH: Add more visible Branding

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#490]
## Is your feature request related to a problem?
We really would like to get in contact with the people using this module.
Both hosts and regular users.
Mainly so we can get feedback and communicate with our users

## Describe the solution you'd like
1. Add a text with logo on top of the Module Control Panel with links to the project page and the wiki
2. Add branding to the bottom of the module with logo, name and link?
I guess we should make this optional?

**Comment by Timo-Breumelhof** [comment]
@WillStrohl @johnhenley what about 2? 
"Forum software: ...." or something alike?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Sorry, I did not notice you had already logged this one..

**Comment by johnhenley** [comment]
> @johnhenley Sorry, I did not notice you had already logged this one..

No problem. You did say you were going to do it so I should not have

**Comment by johnhenley** [comment]
> @WillStrohl @johnhenley what about 2? 
> 
> "Forum software: ...." or something alike?

I would say 1 only. 2 is too invasive I think.

**Comment by Timo-Breumelhof** [comment]
Ok let's start with 1 But  I would also like a user to simply add a line that states whet module was used (I would use that..)

**Comment by Timo-Breumelhof** [comment]
@johnhenley @WillStrohl First setup:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/00f7b47c-d746-4d8d-8168-ab3b1fa733dd)


Texts from a RESX file

**Comment by Timo-Breumelhof** [comment]
Test dump:

```
<style>
	.dcf-community-msg{
		border: solid 1px #ddd;
		padding: 1em;
		margin: 0 0 1em;
		display:flex;
		flex-wrap: wrap;
		gap: 0 2em ;
		align-items: center;
	}
	.dcf-community-msg .dcf-community-msg-logo{
		width: 300px;
	}
	.dcf-community-msg-text{
		min-width: 300px;
	}
	
</style>

<div class="dcf-controlpanel">

<div class="dcf-community-msg">
	<img class="dcf-community-msg-logo" src="/DesktopModules/ActiveForums/Images/Branding/Logo/DNN-Community-Forums-Logo-Horizontal.png" alt="DNN Community Forums Module" />
	<div class="dcf-community-msg-text">[RESX:Community-Message]</div>
</div>
```

**Comment by johnhenley** [comment]
> @johnhenley @WillStrohl First setup:
> 
> 
> 
> ![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/00f7b47c-d746-4d8d-8168-ab3b1fa733dd)
> 
> 
> 
> 
> 
> Texts from a RESX file

NICE !!
