### ISSUE TITLE
BUG: Quick reply is very wide and misses a submit button

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#491]
## Describe the bug
This is an issue in the new template.

## Software Versions
- DNN: 09.10.01
- Module: 08.00.00

## To Reproduce
1. Try the quick reply with the new Template

## Expected behavior
normal width and button should show..

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/b4583405-9ed7-4b20-92ef-1036566cedbe)

**Comment by johnhenley** [comment]
@Timo-Breumelhof do you need me to do anything on this? when I did the PR #436, I had the font-awesome icons, and the quick reply looked like this:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/82c43e6c-dc80-45d2-b0af-cb6b14f4b013)

**Comment by Timo-Breumelhof** [comment]
@johnhenley No, not for now, I'll work on this one next week

**Comment by Timo-Breumelhof** [comment]
Fixed in new Default Theme
