### ISSUE TITLE
BUG: User Settings are cached?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#492]
## Describe the bug
When I change my settings, I have to clear the DNN cache for it to actually change

## Software Versions
- DNN: 09.10.02
- Module: 08.00.00

## To Reproduce
1. Go to My Settings
2. Check Hide Avatars [x]
3. Save
4. Refresh the page, avatars are still shown
5. Even with all template caching off

## Expected behavior
You should not have to restart DNN for this

**Comment by johnhenley** [comment]
There are still some issues with the 'my settings' control.

**Comment by johnhenley** [comment]
@Timo-Breumelhof @WillStrohl Should "my settings" even show signature options if that option is disabled for the forum in the module settings? Not a huge priority, but I noticed it when testing. You can update your signature and never see it because the module settings has signatures turned off...

**Comment by WillStrohl** [comment]
@johnhenley That's a great find...  My first thoughts is to show it, but have a tooltip that says it's disabled in the settings.  Thoughts, @Timo-Breumelhof?

**Comment by Timo-Breumelhof** [comment]
Or greyed out with a message?

**Comment by WillStrohl** [comment]
That would be what I mean about being disabled.  😁
