### ISSUE TITLE
Community Theme Source

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#503]
## Is your feature request related to a problem?
**Please describe.**
I think we should exclude the following files from the module install package.

## Describe the solution you'd like
I'm talking about the files for less parsing:

```
gulpfile.js
package.json
package-lock.json
```

I see two options for users that want to "fork" / create their own version of the Theme
A. They download the files from Github
B. We wrap the source files in a "source.zip.resources" and deliver that with installing?

Opinions?

**Comment by johnhenley** [comment]
@Timo-Breumelhof you know your community better than I do :) but I would say option B is better IMHO.

**Comment by Timo-Breumelhof** [comment]
I guess B is the better option too.
I'll try to "gulp" that..

**Comment by WillStrohl** [comment]
I'll defer to you two on this one. Both options can work. :)

**Comment by Timo-Breumelhof** [comment]
I'll create a separate issue for "exclude gulp files in Installer"
