### ISSUE TITLE
BUG: Place new module leads to two modules?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#520]
## Describe the bug
When I placing a DNN module, normally there's a floating box to place it.
When I do this with the Forums module I also see the module already placed and when I drop the floating Icon, I have two modules.

## Software Versions
- DNN: 08.00.00 (upgraded)
- Module: 09.10.01

## To Reproduce
1. Place the Community Forums Module
2. See:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/5caa0ec4-d689-4ac7-b309-82e6bcc2789c)

Result:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/1908c7c3-e4e0-47fd-a1fc-8d6cb81a6ad7)

## Expected behavior
One module should be placed

Can others reproduce this?

**Comment by Timo-Breumelhof** [comment]
Caused by having two module definitions in one?

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/ee40d9f0-9ac1-41e3-954d-fd929207d73e)

**Comment by Timo-Breumelhof** [comment]
FYI, I also see this in moduledefinitions:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/04c6486e-87bc-4d93-849d-d9201691d44c)

"Viewer" and "What's new" still  have the old name

**Comment by johnhenley** [comment]
@Timo-Breumelhof i do encounter this occasionally and I assume it's not specific to the forums module since it actually happens as part of the persona bar / adding a module process. When it happens (you see the start page instead of the floating icon), I refresh the page and the module disappears. If you proceed as you did, then you probably ended up installing the module twice in the same cycle, which means the update sql and upgrade code in the module runs twice concurrently.

**Comment by Timo-Breumelhof** [comment]
Ok, I'll try a fresh upgrade later as it might be caused by me installing  8.0.0 10 times

**Comment by johnhenley** [comment]
@Timo-Breumelhof @WillStrohl 
Do you think this might be somewhat related? It sounds very similar. 

https://github.com/dnnsoftware/Dnn.Platform/issues/5377

**Comment by Timo-Breumelhof** [comment]
@johnhenley No I don't think so, that's Azure specific it seems

**Comment by johnhenley** [comment]
> Caused by having two module definitions in one?
> 
> 
> 
> ![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/ee40d9f0-9ac1-41e3-954d-fd929207d73e)
> 
> 

@Timo-Breumelhof it does look like you picked up an extra module definition at some point while testing the extension upgrade (which went through several iterations).

**Comment by johnhenley** [comment]
@Timo-Breumelhof I was able to duplicate this; it's a scenario we didn't test during upgrades. We tested 7->8 *upgrade* of an existing module, and v8 fresh install; both resulted in correct behavior. What we *didn't* test was an existing v7, upgraded to v8, and then adding the module to a page (I guess I naively assumed that if you had v7 and are upgrading to v8, you already have a forums module running, and wouldn't need to install another one. The scenario as duplicated is 1) install 7.0.12, then install 8.00.01. That results in two ModuleDefinitions as you noted, and duplicates the module when you put it onto a page. I will fix this for 08.01.00.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I noticed an issue with the fix I think.
After I upgrade the module to 08.01.00 the exiting Forums module is gone.
I guess the module was placed as "Active Forums, which does not exist any more after the upgrade ?
08.01.00 built from dev. and installed on my test site.. (over 08.00.01)

**Comment by johnhenley** [comment]
> @johnhenley I noticed an issue with the fix I think.
> 
> After I upgrade the module to 08.01.00 the exiting Forums module is gone.
> 
> I guess the module was placed as "Active Forums, which does not exist any more after the upgrade ?
> 
> 08.01.00 built from dev. and installed on my test site.. (over 08.00.01)
> 
> 

@Timo-Breumelhof I will retest and see what I can figure out. Seems like this is going to keep haunting me :)

**Comment by johnhenley** [comment]
@Timo-Breumelhof fix is in PR #731
