### ISSUE TITLE
ENH: Subscribe to Forum texts shorter

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#523]
## Is your feature request related to a problem?
I think the subscribe and unsubscribe text are a bit long..

## Describe the solution you'd like
Check this box to subscribe to this topic > Subscribe to this topic
Check this box to subscribe to this topic ? Unsubscribe from Topic

**Comment by WillStrohl** [comment]
Less is more.  I like this.
