### ISSUE TITLE
ENH: align dbtypes for forum/group keys

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#536]
## Is your feature request related to a problem?

Security and settings keys for Forums/Groups are used in database procedures, and are not using the same database type, resulting in implicit conversion during procedure executions. 

activeforums_Settings.GroupKey is nvarchar
activeforums_Security.SecurityKey is nvarchar

activeforums_Forums.ForumSettingsKey is varchar
activeforums_Forums.ForumSecurityKey is varchar

activeforums_Groups.GroupSettingsKey is varchar
activeforums_Groups.GroupSecurityKey is varchar

## Describe the solution you'd like
Align these types to be consistent.

**Comment by WillStrohl** [comment]
As far as I remember, `NVARCHAR` is always a more flexible option, but these values don't necessarily need the flexibility.  This is why I use `NVARCHAR` for anything that might be localized.

**Comment by johnhenley** [comment]
> As far as I remember, `NVARCHAR` is always a more flexible option, but these values don't necessarily need the flexibility.  This is why I use `NVARCHAR` for anything that might be localized.  

Agreed. No need for nvarchar for these. Easy enough to fix but very low priority.
