### ISSUE TITLE
Theme.css does not get loaded after upgrade

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#543]
## Describe the bug
I just built the current dev branch, and upgraded from v7 and the Theme looks weird.
This might be related to the issue @WillStrohl just reproduced and is going to log (module settings not working)

## Software Versions
- DNN: 08.00.00 (dev @ 2023-10-09)
- Module: 09.10.02

## To Reproduce
1. Upgrade the module from 7 to 8 using a custom theme
2. Open the page source, no theme.css loaded

## Screenshots

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/c5440da1-eefe-4706-afe8-4e3b93cd1131)

## Error log (admin log)
----------------------------------
AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:cef23ca1-c8c3-40bf-b79d-2dd243b83bbc

AssemblyVersion:

PortalId:-1

UserId:-1

TabId:-1

RawUrl:

Referrer:

UserAgent:

ExceptionHash:CldcC4/YZwk/frHKvGpNxFtagOk=

Message:TemplateId

StackTrace:

   at System.Data.ProviderBase.FieldNameLookup.GetOrdinal(String fieldName)
   at System.Data.SqlClient.SqlDataReader.GetOrdinal(String name)
   at System.Data.SqlClient.SqlDataReader.get_Item(String name)
   at DotNetNuke.Modules.ActiveForums.TemplateController.FillTemplateInfo(IDataReader dr)

InnerMessage:

InnerStackTrace:

Source:System.Data

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: TD801
----------------------------------

**Comment by johnhenley** [comment]
Merge in PR 540. It contains an "oops" fix

**Comment by johnhenley** [comment]
Fixed in #540

**Comment by johnhenley** [comment]
Fixed in #540

**Comment by Timo-Breumelhof** [comment]
@johnhenley ok sorry, I did not see the connection with your PR before..
