### ISSUE TITLE
TASK: Include themes/readme.md in installation

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#549]
Community Forums now includes a readme.md in the themes folder. This file needs to be included in the install.

**Comment by WillStrohl** [comment]
I'm curious... Why are we including a `README` for this instead of using the Wiki?  It seems like we're going to split/duplicate effort on documentation.  If we want a `README` there, it could point to the documentation so it's only required to update it in one place.

**Comment by Timo-Breumelhof** [comment]
We could but My idea was that someone editing the files is directly confronted with some docs.
But we could also link to the wiki...

**Comment by WillStrohl** [comment]
I just see us sometimes missing updates there, and others maybe not knowing where all of the information is.  Not to mention others maybe not knowing to update this file as well (if anyone else contributes).  🤷🏽‍♂️

**Comment by Timo-Breumelhof** [comment]
I'm fine with moving this to the wiki and linking to it
