### ISSUE TITLE
Make toolbar icons more clear

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#550]
## Is your feature request related to a problem?
**Please describe.**
See: 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/9ea113d7-f68f-49a7-9c03-a047cd50780d)

I think this would be better:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/3b0384fc-dcd5-489b-a84c-48d61cc5b5f2)

## Describe the solution you'd like

```
<a href="https://dnnmoduletest3.tb.40fdev.me/activeforums/"><i class="fa fa-home fa-fw fa-blue"></i><span class="dcf-link-text">Forums</span>
<a href="https://dnnmoduletest3.tb.40fdev.me/activeforums/Home/afv/grid/afgt/unanswered"><i class="fa fa-comment-o fa-fw fa-blue"></i><span class="dcf-link-text">Unanswered</span>
<a href="https://dnnmoduletest3.tb.40fdev.me/activeforums/Home/afv/grid/afgt/notread"><i class="fa fa-eye-slash fa-fw fa-grey"></i><span class="dcf-link-text">Not Read</span>
<a href="https://dnnmoduletest3.tb.40fdev.me/activeforums/Home/afv/grid/afgt/mytopics"><i class="fa fa-user fa-fw fa-grey"></i><span class="dcf-link-text">My Topics</span>
<a href="https://dnnmoduletest3.tb.40fdev.me/activeforums/Home/afv/grid/afgt/activetopics"><i class="fa fa-fire fa-fw fa-grey"></i><span class="dcf-link-text">Active Topics</span>

```

**Comment by johnhenley** [comment]
@Timo-Breumelhof the icon choices look fine. I can make them in the code if you send me the classes. However, 
thinking about this more in light of our conversation yesterday and how everything should be "templatable". Particularly the two toolbars. I really cringe and resist trading out one FA class for another one which requires code change and recompile etc. Doing it properly gives designers the option to swap icons on their own if they choose. Do we take this on now or defer?

**Comment by WillStrohl** [comment]
Good question...  I'm leaning toward putting it off to see if there is any demand for it.  There's no sense in spending the time if no one will notice.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I agree for version 9 ok? ;-)

**Comment by johnhenley** [comment]
Sorry I might have been unclear. 

We can change the icons now to ones that @Timo-Breumelhof chose because they are more appropriate. That's easy enough. 

I agree we shouldn't update to a different method of selecting an icon (i.e., doing it completely in the css rather than emitting an fa-xx class from code) until a future release and we all agree it's worthwhile. And I'm way out of my league here.
