### ISSUE TITLE
BUG: Exception during upgrade when renaming _default folder to _legacy

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#554]
## Describe the bug
During an upgrade from pre-8.0 releases, the `themes/_default` folder is renamed to `themes/_legacy`. However, there is now updated themes content being installed from the `_legacy` folder, which causes an exception during the upgrade process. Need to change the upgrade logic to move files rather than rename the folder.

## Software Versions
- DNN: 09.12.00
- Module: 08.00.00 (dev build)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/c126cd5d-df3f-42fb-865a-330772585fb4)

**Comment by WillStrohl** [comment]
@johnhenley  FYI - We'll want to find someone to test this in an Azure instance once we have an RC ready.  CC: @Timo-Breumelhof
