### ISSUE TITLE
ENH: Install and load FontAwesome locally rather than from CDN

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#556]
## Is your feature request related to a problem?
Some installations have DNN installed in an intranet and may not have internet access to the CDN from which FontAwesome is currently loaded. 
## Describe the solution you'd like
Include FontAwesome in the install package and load it locally.

**Comment by WillStrohl** [comment]
Are you proposing that it's always loaded locally, or should that be a setting?  I do realize many larger companies are banning CND links these days.

**Comment by Timo-Breumelhof** [comment]
Always local for now was the idea for that exact reason and internal intranets..

**Comment by Timo-Breumelhof** [comment]
@WillStrohl We are now using the Client Resource manager, if "Everyone else" does that too this is not really an issue

See: https://github.com/DNNCommunity/Dnn.CommunityForums/wiki/Dependencies
