### ISSUE TITLE
Forum Subscription option missing with new community-default theme/templates

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#585]
## Describe the bug
Option to subscribe to forum is missing.

## Software Versions
- DNN: 09.12.00
- Module: 08.00.00 (dev)

 Older version:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/1ce7584c-478b-475d-8608-9ee44a8ad2b7)

New version:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/74fbfcb3-7609-479b-9178-10f9038296c6)

**Comment by Timo-Breumelhof** [comment]
Hmm, used to be there a week ago, I must have made a copy paste error when I moved the search around..
Thanks for logging.
