### ISSUE TITLE
Button to subscribe to all forums

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/Dnn.CommunityForums#593]
## Is your feature request related to a problem?
**Please describe.**
I am missing a lot of action as I did not subscribe to all the forums. 

## Describe the solution you'd like
A button that will subscribe me to all forums

**Comment by johnhenley** [comment]
Great suggestion!

**Comment by johnhenley** [comment]
adding a new toolbar link that lets you manage your subscriptions to:

- topics: displays topics you are subscribed to, and lets you uncheck them
- forums: display available forums based on your security and lets you check/uncheck which ones you want
@Tychodewaard do you want a "subscribe all" button that selects them all, or is just the ability to have them all on one form sufficient?

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/f231450f-4e7e-4146-98e0-25f1c4b66c9e)
