### ISSUE TITLE
Disabled Security Icons should be disabled

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#61]
## Describe the bug
When a Forum inherits the security from it's group, the security icon seem to be clickable but they are not.
This makes the interface confusing.

## Software Versions
- DNN: 09.08.00
- Module: 06.05.00

## To Reproduce
1. Create a group
2. Create a forum and set it to inherit settings
3. Go to the Forums Security, the icon seem clickable but they are not.

## Expected behavior
Make the icons grey of make sure you see they are not clickable.

## Screenshots
![image](https://user-images.githubusercontent.com/8999382/106478720-c9091b80-64a9-11eb-854b-cd288ec24290.png)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I think this was fixed a long time ago; you can't even see security tab if you're inheriting security. Are you OK for me to close this?

**Comment by Timo-Breumelhof** [comment]
@johnhenley yes
