### ISSUE TITLE
ENH: Split "inherit" in ControlPanel

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#611]
## Is your feature request related to a problem?
I think the most common "advanced" use case is that you use the same Theme for all Sub-Forums but change the security settings per Forum. This is currently not as easy s it could be IMO. 

## Describe the solution you'd like
You can "inherit" a parent settings:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/7393bf19-8f2b-4d9f-8944-3d7c41fd226b)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/ba364cb1-6ac4-447d-ac76-a493d6d1074a)

But in the use case above (which we use on the community site) that means you have to set everything, including the templates for sub forums.

I think it would be nice if you could inherit
- Templates
- Security
- Other settings

Individually as I think the most common use case is to change the security for a sub-forum.

## Describe alternatives you've considered
Remove individual settings for templates altogether (which seems like an OK option too)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I will do this in conjunction with #536
