### ISSUE TITLE
Like notifications

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#632]
Follow on to #172. Notify original poster when user "likes" their post
- Add column to user settings 
- add module or forum settings for default opt-in 
- Add user setting to UI for opt-in to like notifications -- default to
Yes or No based on above 
- add process type to send like notifications from process queue new in 8.1)
- Add like notifications template 
- update like controller to add notifications to queue

**Comment by Tychodewaard** [comment]
Can I upvote this one? Together with the ability to see who liked a post, it would improve the activation / engagement on the forums.

**Comment by johnhenley** [comment]
Should like notifications be opt-in or opt-out?

**Comment by johnhenley** [comment]
> Should like notifications be opt-in or opt-out? Or does it need to be a configuration setting per module instance or even per forum?

@Timo-Breumelhof @WillStrohl opinion on opt-in vs opt-out?

**Comment by Timo-Breumelhof** [comment]
Opt-out
