### ISSUE TITLE
Create new release 8.1

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#633]
Update versions In manifest 
Create empty sqldataprovider file

**Comment by Timo-Breumelhof** [comment]
@johnhenley  Title says 08.01.. ?

**Comment by johnhenley** [comment]
> @johnhenley  Title says 08.01.. ?

Isn't 08.01 = 8.1 ?

**Comment by Timo-Breumelhof** [comment]
Oh sorry, I misread it. :-( 
I thought the milestone was 08.00.01 and the title 08.01.00 (8.1)
