### ISSUE TITLE
Update copyrights

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#634]
Update copyright in source files to 2024

**Comment by robertbravery** [comment]
HI All, First time. 
Is this just a Search and replace. Seems simple enough, or am I missing something.

**Comment by johnhenley** [comment]
> HI All, First time. 
> 
> Is this just a Search and replace. Seems simple enough, or am I missing something.

Hi Robert and welcome! Yes I think it's fairly simple. I usually just do a search and replace with a regular expression against source files.

**Comment by johnhenley** [comment]
@WillStrohl do you want me to do this?

**Comment by WillStrohl** [comment]
@johnhenley Hahaha!  I was just preparing the module for the 8.1 RC and noticed this and just did it.  😆

It'll be done with my 8.1 release PR.
