### ISSUE TITLE
Site Search returning incomplete URLs when using Friendly URLs

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#643]
## Describe the bug
Site searches return URLs that don't correctly resolve because they don't include the page portion of the URL.

## Software Versions
- DNN: 09.13.00
- Module: 08.00.00

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/63a4af49-432f-4bff-94a5-9a69b5925fb8)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/180459d2-1c1e-4fa5-b210-dbf4a6a66838)

## Additional context
Tangentially related to #514

**Comment by johnhenley** [comment]
@WillStrohl I have a PR ready for this but it requires a stored procedure change. Do you want this to be 8.0.2 or just include in 8.1?

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof do you want this for 8.0.2, or 8.1 ?

**Comment by WillStrohl** [comment]
8.0.2 is fine with me.
