### ISSUE TITLE
Topic Subscribe/Quick Reply Subscribe checkboxes have different values

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#649]
## Describe the bug
The subscribe/unsubscribe boxes are different values on topic view and quick reply. They should match.

## Software Versions
- DNN: 09.13.00
- Module: 08.00.01

## To Reproduce
1. select an existing topic.

## Expected behavior
They should match

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/9827a5b5-689c-487f-85cb-0b99a0bfbb96)

**Comment by johnhenley** [comment]
@WillStrohl I have a fix for this if you want a PR. I think this and #643 for search URLs probably warrants an 8.0.2 release just to get them fixed quickly.

**Comment by johnhenley** [comment]
@WillStrohl @Timo-Breumelhof do you want this for 8.0.2, or 8.1 ?

**Comment by WillStrohl** [comment]
8.0.2 is fine with me.
