### ISSUE TITLE
Misaligned columns in topic results

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#656]
## Describe the bug
Inconsistent table columns/layout in "active topics" and other results (using af-search-results).

## Software Versions
- DNN: 09.12.00
- Module: 08.00.01

## To Reproduce
1. Fresh install of Forums
2. Enter several topics with varying title/subject lengths
3. Go to 'active topics' and will see misalignment of results

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/dab3844f-9c59-46f0-9db7-c73c146bed47)

This is what it looks like on my site:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/c60951da-19c0-4302-bd33-e673d9daefc1)

## Additional context
@Timo-Breumelhof the results are displayed using tables within tables, which is problematic, I am sure. We have discussed that the ultimate fix for this is for the results to be templated, which will happen in a future release. But in the meantime, if there is some quick CSS fix, please see if you can do anything. 

What looks to happen is that the browser is applying a CSS rule:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/f7619a19-00b2-401d-8edb-027c5a08c425)

I did a workaround on my site by adding this to the `/themes/community-default/custom/theme.css` (I LOVE that feature for layering in the custom CSS 😊) This kinda fixes it by adding this, but not really sure what I’m doing 😊
`.afgrid {table-layout: fixed;}`

**Comment by Timo-Breumelhof** [comment]
@johnhenley is this still an issue with the new Themes?
