### ISSUE TITLE
"Active Forums What's New" module is upgraded despite "Package Installation aborted"

### ISSUE THREAD

**Issue by eoghanon** [DNNCommunity/Dnn.CommunityForums#67]
## Describe the bug
It appears that a failed attempt to upgrade to the latest version of the module (and resulting in "Package Installation aborted") does not stop the installation of the latest version of "Active Forums What's New" module. After such a failed attempt to upgrade to v6.5 the list of DNN extensions installed shows Active Forums as being back at (pre-upgrade) version but the "Active Forums What's New" module is listed as being installed at v6.5. 

## Software Versions
- DNN: 09.04.04
- Module: 06.05.00

## To Reproduce
1. A failed attempt to upgrade to v6.5 of DNN.CommmunityForums from v5.2.2 (failure described as [issue #66](https://github.com/DNNCommunity/Dnn.CommunityForums/issues/66)) resulted in "Package Installation aborted"
2. When afterwards the list of DNN extensions is accessed (via the Persona Bar) it shows Active Forums as being back at v5.2.2 (expected behaiour) however the "Active Forums What's New" module is now at v6.5 (unexpected behaviour). 

## Expected behavior
"Active Forums What's New" module would be rolled back to the version it was just before the failed upgrade took place.

**Comment by Timo-Breumelhof** [comment]
As the modules are installed separately (It's one package, but it's a multi-module package), I don't think this is an easy fix for this and To be honest, I wonder if there will be anyone willing to spend time on re-configuring the install process for this.
(not the error that caused the install to fail, but the fact that "Active Forums What's New' is @ 6.5)

**Comment by hismightiness** [comment]
First, thank you for logging this as two issues...  Yay!  🥇 

What Timo said...  There's technically not an official upgrade path, but this is also a complex module.  

As for rolling back, there's no concept of an upgrade/install rollback in most systems, including DNN - only install, upgrade, and uninstall.  Instead, you should always back up the website prior to anything you haven't tested.  Hopefully, you took a backup that you can restore and start over?  

In reviewing the previous releases, perhaps the upgrade path from 5.2.2 should maybe be:  

- From 5.2.2 to [6.3.0](https://github.com/ActiveForums/ActiveForums/releases/tag/v06.03.00)  
- From 6.3.0 to [6.3.3](https://github.com/ActiveForums/ActiveForums/releases/tag/v06.03.03)  
- From 6.3.3 to [6.5.0](https://github.com/DNNCommunity/Dnn.CommunityForums/releases/tag/06.05.00)  

(That upgrade path is only an educated guess.  You may be able to skip 6.3.3 safely, for instance.)  

Beyond that, if you're in a spot where you're unable to restore the module, I believe your only course of action is to leave things as-is and upgrade this module more incrementally.  I'd suggest perhaps trying this:

1. Restore the site locally (or somewhere else) to more safely follow the remaining steps below.  
2. Backup the site.  
3. Manually update the module version for the `Packages` table for the `Active Forums What's New` module to the same version of the `Active Forums` module.  
4. Follow the suggested upgrade path above.  
5. Before upgrading, modify the upgrade package to remove the `Active Forums What's New` module from the DNN manifest (`.dnn`) file.  
6. When you get to version 6.5.0, you can leave the `Active Forums What's New` module in the manifest unchanged.  
7. Test.  
8. Do it again in production.  

If anyone else has a better idea, we're all ears.  :)

**Comment by Timo-Breumelhof** [comment]
As this is an edge case we will not spend time on this, if someone want to fix this, let us know and we will re-open the issue

**Comment by hismightiness** [comment]
Agreed. Thanks, Timo.
