### ISSUE TITLE
Summertime

### ISSUE THREAD

**Issue by norschu** [DNNCommunity/Dnn.CommunityForums#678]
The changeover from summer or winter time is not carried out automatically. 

We use "DNN Community Forums 7.0.1.0". The changeover from summer or winter time is not carried out automatically. 
Is there a configuration option there?

**Comment by johnhenley** [comment]
@norschu the forums module was updated in version 7.0 to store and operate internally using UTC. Any dates displayed to users in the UI and in email notifications are adjusted using the time zone in their user profile.

**Comment by johnhenley** [comment]
> @norschu the forums module was updated in version 7.0 to store and operate internally using UTC. Any dates displayed to users in the UI and in email notifications are adjusted using the time zone in their user profile. 


@norschu I am reopening this to investigate what appears may still be a problem. The forums module stores everything in UTC and uses timezone from the user's profile. All good except it appears (at least on dnncommunity.org) that the offset isn't working. 

I posted this at 7:30am my time (EDT). Ut it shows as 6:30
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/db440d63-de9a-47c4-b797-fdb1a41cd19c)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/dadc6cd0-6eef-4601-a1e6-e87b62af3a7c)
