### ISSUE TITLE
BUG: Error from the browser while subscribing to a new topic

### ISSUE THREAD

**Issue by warkhos** [DNNCommunity/Dnn.CommunityForums#697]
## Describe the bug
I recently created a new topic on the forums module at DNN community website, before submitting the topic I tried to subscribe to the topic itself in order to get notifications once somebody replies back but I got a browser error (check screenshot below).

## Software Versions
I don't have this information because the problem its with the Forum module at the DNN Community website, I guess will be the latest version for Forums module and the latest DNN version.

I was using FireFox version 123.0.1 (64-bit)

## To Reproduce
1. Create a new topic in forums module
2. Before submitting, check the checkbox for subscribing at the bottom of the page.
3. You'll get the error either you check or uncheck the checkbox control.

## Expected behavior
To successfully subscribe to the new created topic.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/121067025/9629c1e4-5cbe-4d42-a6b2-3fb2d5711ab5)

## Error log
I don't have access to do this.

## Additional context
Not additional context at this point.

**Comment by Timo-Breumelhof** [comment]
Hmm, right. That's probably because the topic does not exist yet.. 
Right @johnhenley ?

**Comment by Timo-Breumelhof** [comment]
And thank you for reporting this @warkhos

**Comment by johnhenley** [comment]
@warkhos thanks for reporting this. This is a valid behavior and should work exactly as you described. I will fix it.
