### ISSUE TITLE
DNN - preventing Self-XSS jquery security vulnerability

### ISSUE THREAD

**Issue by johnngoit** [DNNCommunity/Dnn.CommunityForums#7]
Open any dnn website in any browser in developer mode(F12).  In the console enter command: $("<img src=x onerror=prompt(123)>")

![image](https://user-images.githubusercontent.com/13056272/73091860-8ecd6d00-3e98-11ea-8ae0-5d42d22234e0.png)

This self-xss cross site is a security vulnerability is disabled in most of the website out there after update their jquery version later than 1.6.3.   But it looks like dnn sites still to have the issue.

We're using dnn version 9.2.2.  Any dnn versions that's already have this issue fixed?

We would be very appreciate if any dnn experts can give us advice or direction on how to resolve this issue.

Sincerely,

JN

**Comment by hismightiness** [comment]
Have you tried since upgrading to DNN 9.6.2 or higher?

**Comment by Timo-Breumelhof** [comment]
@hismightiness IMO this is not specific to Active Forums and we can close it, right?

**Comment by hismightiness** [comment]
@Timo-Breumelhof That's what I was thinking and why I asked my follow-up question.  It's been two weeks, so I'm guessing this is a stale issue anyway.

**Comment by hismightiness** [comment]
Unless we can get any confirmation from anyone else or @johnngoit , we'll close this when this pending release is published.
