### ISSUE TITLE
Prevent toolbar overcrowding

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#703]
## Is your feature request related to a problem?
**Please describe.**
As we add more filters to the toolbar, this also makes it less clear due to overcrowding the toolbar.

## Describe the solution you'd like
I think we could add a filter link with an (html css) dropdown, containing 
- unanswered
- not read
- Announcements
- active topics
- most liked
- most replies
- 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/97b4a5ef-6c13-4f96-80fc-9d26e0b19f98)

The only disadvantage I see that from a Forum manager point of view it would be nice if you could set what ends up where.
But I guess that's for a later stage..

## Describe alternatives you've considered
none

## Additional context
see also #701

**Comment by johnhenley** [comment]
@Timo-Breumelhof that would be great. An administrator has control--since toolbar is templated--over which filters they want to display.

**Comment by Timo-Breumelhof** [comment]
I think so, I'll have a look

**Comment by johnhenley** [comment]
> @johnhenley what do you think.. (where to add the JS)
> 
> A. Make part of the module
> 
> B. Make is part of the themes
> 
> 
> 
> Or maybe re-use the code for the panel collapse?

It's just html and css as part of toolbar template and goes in the theme imho. The module shouldn't dictate what is shown. For example, "most likes" or "announcements" might not be relevant if a site doesn't use those features so they could be commented out or removed from template in the sites's theme. Does that make sense?

**Comment by Timo-Breumelhof** [comment]
I'll first built it and then we'll decide :-) @johnhenley
