### ISSUE TITLE
Forum decodes HTML entered as Encoded HTML

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#73]
## Describe the bug
The Forum Decodes HTML entered in the WYSIWYG editor (with the intention to show it as text).
This prevents users from posting code in the forums (is being stripped out right now)

## Software Versions
- DNN: 09.08.01
- Module: 06.05.01

## To Reproduce
1. Create a post (with HTML allowed in the forum settings)
2. In the CKEditor post `<span>test</span>` (not in the Source)
3. Save the post, you will see `test` rendered by the forum
4. Edit the post, you will only see "test" in the CkEditor, but the span has been placed in the HTML source instead of stored as encoded HTML.

## Expected behavior
Encoded HTML should not be converted, but left as entered

**Comment by Timo-Breumelhof** [comment]
IMO the Decode on this line should be removed.
https://github.com/DNNCommunity/Dnn.CommunityForums/blob/aada41b9b2fa1b02711c92191e6aa1e832c62603/class/Utilities.cs#L553

After that <p>text</p> stays HTML encoded and is save the way it should be.
But when you Edit after that, the HTML is decoded again (in the editor), not sure if that's by module or CkEditor

**Comment by hismightiness** [comment]
I'm not sure I understand what's happening here.  Maybe something is missing the Steps to Reproduce? 🤔

**Comment by Timo-Breumelhof** [comment]
@hismightiness ok, edited, better now? BTW I found one part of the fix, working on the other part..
