### ISSUE TITLE
ENH: Improve HTML of [AF:CONTROL:STATUSICON]

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#743]
## Is your feature request related to a problem?
[AF:CONTROL:STATUSICON] currently renders this:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/bb85d85d-49a1-446f-9934-2c7090180104)

This is in he template:

<div class="flex-grow-1">
	<h1 class="dcf-title h2 mt-0">[AF:CONTROL:STATUSICON]<span class="dcf-topic">[SUBJECT]</span></h1>
</div>

The extra div is not needed and makes  CSS styling more difficult.
This is just an example, i might be good to also check other Icons for the template rendered

## Describe the solution you'd like
Instead of 

`<div><i class="fa fa-status0 fa-red fa-2x"></i></div>`

simply render

`<i class="fa fa-status0 fa-red fa-2x"></i>`

**Comment by johnhenley** [comment]
@Timo-Breumelhof. For templates, those are moving to files for all control-type templates. But for smaller HTML snippets/token replacements, should we move them to a token.config key/value file or to resources rather than have them be hard-coded? So an example, name="[AF:CONTROL:STATUSICON][SUBJECT]" value="<i class=\"fa fa-status0 fa-red fa-2x\"></i>"

Advantage of resource file is that we could deliver it with initial values, but it can be overridden by a designer. And it pulls more UI stuff out of code. Eventually I think everyone wants to get to razor syntax vs token replacement, but that's much further away.

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think we should use REXS files if there is anything translatable?

**Comment by johnhenley** [comment]
@Timo-Breumelhof do you want to leave it open and just park it on the future milestone?

**Comment by Timo-Breumelhof** [comment]
> @Timo-Breumelhof do you want to leave it open and just park it on the future milestone?

Also OK as a reference maybe?

**Comment by johnhenley** [comment]
> > @Timo-Breumelhof do you want to leave it open and just park it on the future milestone?
> 
> 
> 
> Also OK as a reference maybe?

Sure. Just don't want to lose the context since it's a good issue.

**Comment by johnhenley** [comment]
@Timo-Breumelhof Looking at this in connection with consolidating token replacement logic. 
Which method do you prefer (no critiquing the HTML please):

Method 1 - using resources:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/9e5fad5d-4462-4615-a481-11125d680b29)
This method would keep the code-based approach but move the HTML to resources, so at least the designer has some access to change it.

Method 2 - using conditional template tokens:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/22dcbdb0-19bc-4fee-83f6-a0582512e788)
This method would remove tokens and contained content when a condition is not met, but leave the HTML when a condition is met. Gives the designer more control and lets the designer use the condition token multiple places in the template if they want. We would have to define the tokens based on what is to get shown (like for a "forum status, what are the valid states?). And would require retrofitting this back into existing templates. And it's more coding. Just wanted to give you the idea though...

**Comment by Timo-Breumelhof** [comment]
I prefer 2.
It's more logical IMO as it keeps al design stuff in one place and all "text" stuff in another.
I like the flexibility of [WHEN...] a lot..

BTW I now have a "nag about HTML" reputation?

**Comment by Timo-Breumelhof** [comment]
Maybe using

[DCF:FORUM:TOPICS:HASNEW]
[DCF:FORUM:TOPICS:NONEW]
[DCF:FORUM:FORBIDDEN]

could maybe make it simpler and processing easier?

**Comment by johnhenley** [comment]
> I prefer 2.
> 
> It's more logical IMO as it keeps al design stuff in one place and all "text" stuff in another.
> 
> I like the flexibility of [WHEN...] a lot..
> 
> 
> 
> BTW I now have a "nag about HTML" reputation?
> 
> 

Just to be clear. If we go with #2, do we force as a breaking change or do we have to support old token and html injection for anyone who doesn't use delivered templates?

**Comment by Timo-Breumelhof** [comment]
@johnhenley If possible I would say we add a shorthand token that loads de default template?

[POSTICON]

loads a "conditional" structure as shown above
But for your example I do wonder how much work these conditions are related to the fact that there are rendering engines that have conditions built in..? Maybe subject for a team meeting discussion.. ;-)

**Comment by johnhenley** [comment]
> @johnhenley If possible I would say we add a shorthand token that loads de default template?
> 
> 
> 
> [POSTICON]
> 
> 
> 
> loads a "conditional" structure as shown above
> 
> But for your example I do wonder how much work these conditions are related to the fact that there are rendering engines that have conditions built in..? Maybe subject for a team meeting discussion.. ;-)
> 
> 

To paraphrase..., "don't invent more tokens--our energy would be better spent integrating/adopting a better templating syntax (razor)"?

**Comment by Timo-Breumelhof** [comment]
Well, maybe, what do you think?
