### ISSUE TITLE
ENH: Default theme > Align Subscribers to the right

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#765]
## Is your feature request related to a problem?
**Please describe.**
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/7692deb4-2d2d-4f04-8cb3-dad6ef654419)

**Comment by Timo-Breumelhof** [comment]
@johnhenley I think we should probably also change the "dcf-subscribe" CSS Class to "dcf-topic-subscribe"?

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/06101d5a-3d76-42f9-b8b5-6f61c87d9032)

**Comment by Timo-Breumelhof** [comment]
@johnhenley it's always good to be able to make a distinction.
The ideal option is dcf-subscribe for everything related and en extra class with a specific class for that item

like: dcf-subscribe dcf-forum-subscribe

**Comment by johnhenley** [comment]
> @johnhenley it's always good to be able to make a distinction. The ideal option is dcf-subscribe for everything related and en extra class with a specific class for that item
> 
> like: dcf-subscribe dcf-forum-subscribe

ok. if you want to change, you can change QuickReply.ascx and TopicView.ascx templates.
