### ISSUE TITLE
ENH: Link to Login when not logged in and viewing a topic 

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#781]
## Is your feature request related to a problem?
This one is just annoying. If I haven't logged in, and I'm viewing a topic, I see a message "you are not authorized to post a reply". Just rude, IMHO :)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/3ffb902e-78f1-4074-8dc5-4a31b13aeeb5)

## Describe the solution you'd like
Put in a link to the login page with a friendlier message.

## Describe alternatives you've considered
I've "solved" this previously by patching in a URL via the resources, but we should just support a standard DNN token for the URL that inserts the URL, and add that to the TopicView template.

**Comment by Timo-Breumelhof** [comment]
Never though of this but I agree this would be much better
