### ISSUE TITLE
Flood control does not take Replies into account

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#81]
## Describe the bug
While fixing https://github.com/DNNCommunity/Dnn.CommunityForums/issues/79
I noticed that replies are not accounted for the check for the flood control.
The reason for this is that while saving a reply, the LastPostDate is not saved.
And that's used for the Flood test.

## Software Versions
- DNN: 09.08.00
- Module: 06.05.01

## To Reproduce
See https://github.com/DNNCommunity/Dnn.CommunityForums/issues/79, notice that Replies don't fire the Flood control.

## Expected behavior
So there are a few questions:
A. Do we want Replies to taken into account for Flood control?
B. If yes, how do we support this?
IMO We should add a DB field LastReplyDate and add that to the Flood check. Thought?

@hismightiness @skamphuis

**Comment by hismightiness** [comment]
Yes, I think we definitely should add that field and include replies in the flood control.
