### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#823]
On the search popup I see the placehoder text:

Search for ...

that has no resource key to provide a translation for

**Comment by vmasanas** [comment]
At the bottom of the page the text "Who's Online" is not translatable

**Comment by vmasanas** [comment]
Under My configuration, none of the texts seems to be translable

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/7d8815ed-98f1-47e5-85e4-7b262f7f1dd6)

**Comment by vmasanas** [comment]
Button "Subscribe to All Forums" is not translatable

**Comment by johnhenley** [comment]
@vmasanas Thank you!!
