### ISSUE TITLE
Issue with z-index

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#824]
When you open the search option on the top right the icons to open/close the forum group appear on top of the popup.

See image
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/4ce19bd8-f78b-4657-9485-667e6b00fc15)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I remember running into same issue with the search popup not covering the 'my settings' page, and had to add this:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/0fc0fb68-1997-4f67-8f2e-2df89d22ac05)

Should this just be added to the module.css:
`.dcf-search-popup{z-index:9 !important;}`
