### ISSUE TITLE
Navigation menu links do not correctly handle multiple languages

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#825]
On a site with multiple languages the links for the top navigation (Forums, moderate, my settings, my subscriptions, ...) always go the default language.

For example on a site I have with Spanish and English:

- click on the spanish flag to set the page in spanish
- I see all items on the navigation bar with the proper translations (Foros, Moderar, Mi configuración, Mis suscripciones, ..)
- Click on "Moderar"
- I see the url goes to 
http://dnnlangmodules.dnndev.me/en-us/Forums/afv/modtopics
while it should be
http://dnnlangmodules.dnndev.me/es-es/Forums/afv/modtopics

**Comment by johnhenley** [comment]
@vmasanas I tested this and had different results.
@Timo-Breumelhof  can you test as well?

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/0ae4341a-6561-4a73-ae0e-326f27a53b43)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/9c0afda7-6f01-4131-9fbd-801ae5b92ea2)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/3be17844-49b8-432e-b7df-6adabd02ce14)


![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/fb065305-5ff4-40e9-9a8f-711a728115a5)

**Comment by vmasanas** [comment]
@johnhenley  see the image below
1. notice how i'm browsing the site in spanish
2. I hover over Moderar (Moderate)
3. See how the url I see there goes back to en-US

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/1d23a39f-094c-4e91-9159-331c6d1c07b6)

**Comment by Timo-Breumelhof** [comment]
@johnhenley Yes I'll try, will probably be next week..

**Comment by johnhenley** [comment]
> > @johnhenley  see the image below
> > 
> > 1. notice how i'm browsing the site in spanish
> > 2. I hover over Moderar (Moderate)
> > 3. See how the url I see there goes back to en-US
> > 
> > ![image](https://private-user-images.githubusercontent.com/4357679/334683081-1d23a39f-094c-4e91-9159-331c6d1c07b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwMjE5MDksIm5iZiI6MTcxNzAyMTYwOSwicGF0aCI6Ii80MzU3Njc5LzMzNDY4MzA4MS0xZDIzYTM5Zi0wOTRjLTRlOTEtOTE1OS0zMzFjNmQxYzA3YjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDUyOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA1MjlUMjIyNjQ5WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NjE0ZGI3YTk4NGMxNmNiYjNjOThlZDg3Y2I0YWRiOTliNmE4MGMxNmNjYzE0ZjQ4ZTU5YzRiNzYwZmQxNmE2MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.dfNve3TfCvFKe1EuJbt7LuSU-FOAb3RcC8VZxmXKvhQ)
> 
> Ok thanks for your patience. I will look into this further. Probably related to caching I think.

@vmasanas thanks for your patience; duplicated and fixed.
