### ISSUE TITLE
Creating a new topic the subject is too small

### ISSUE THREAD

**Issue by vmasanas** [DNNCommunity/Dnn.CommunityForums#826]
When I go to create a new topic the subject input box is very small. It should take at least all available space:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4357679/6d3aabad-c006-4753-b956-166314af6837)

**Comment by vmasanas** [comment]
Same about the Summary btw.

**Comment by Timo-Breumelhof** [comment]
@vmasanas right, good point. Thank you for logging this.

**Comment by johnhenley** [comment]
Would like to get community feedback on the "summary" field. Some people love it but others hate it. It can be removed altogether by removing it from a template but that removes it for everyone using a forum. Should it be a toggle on each forum or per user? Should it be collapsible so it can be used if desired but not take up as much space if you don't want it?

**Comment by valadas** [comment]
On one hand, I think it is nice for SEO, on the other hand one has to think about the summary and then the post details... I don't have a very strong opinion.

**Comment by vmasanas** [comment]
What do other platforms do? I would think that much twice: if this is common in other forums just keep it. If nobody uses it, then drop it.
