### ISSUE TITLE
BUG: French translation incomplete 

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#832]
## Describe the bug
French translations were incomplete (only had first lines of resource file)

## Software Versions
- DNN: 09.13.03
- Module: 08.01.00 RC1

**Comment by valadas** [comment]
> I am happy to take a look upon returning home. I am still in Europe until June 6th...

**Comment by johnhenley** [comment]
> > I am happy to take a look upon returning home. I am still in Europe until June 6th...

Thanks. Interestingly, there appears to be no translation for "Forums" :) ?
