### ISSUE TITLE
8.0.1-RC can't display any forums

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/Dnn.CommunityForums#856]
## Describe the bug
I just installed v8.1.0-rc on a new clean DNN instance. After going through the wizard I got to the list of forums (Sample Forum 1, 2 and 3) but when clicking on any of them, I get the an error.

## Software Versions
- DNN: 9.13.3
- Module: 8.1.0-rc

## To Reproduce
1. Do a clean DNN install.
2. Install 8.1.0-rc1
3. Place the forum module on a page
4. After the wizard, try to click on any forum

## Expected behavior
Should show the forum.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/6371568/12612a91-1a43-4bda-b77b-b4eb041a6c88)

## Error log
```
2024-06-09 19:29:11.186-04:00 [DanielValadasPC][D:4][T:40][ERROR] DotNetNuke.Modules.ActiveForums.Environment - Object reference not set to an instance of an object.
System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Modules.ActiveForums.Controllers.ForumController.GetForumListXML(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumBase.get_ForumData()
   at DotNetNuke.Modules.ActiveForums.ForumBase.SecurityCheck(String secType)
   at DotNetNuke.Modules.ActiveForums.ForumBase.get_CanCreate()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.ParseControls(String Template)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.BindTopics(String TopicsTemplate)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.OnLoad(EventArgs e)
2024-06-09 19:29:11.199-04:00 [DanielValadasPC][D:4][T:40][ERROR] DotNetNuke.Services.Exceptions.Exceptions - FriendlyMessage="[L]Error: DNN Community Forums is currently unavailable." ctrl="DotNetNuke.Modules.ActiveForums.Controls.TopicsView" exc="System.NullReferenceException: Object reference not set to an instance of an object.
   at DotNetNuke.Modules.ActiveForums.Controllers.ForumController.GetForumListXML(Int32 PortalId, Int32 ModuleId)
   at DotNetNuke.Modules.ActiveForums.ForumBase.get_ForumData()
   at DotNetNuke.Modules.ActiveForums.ForumBase.SecurityCheck(String secType)
   at DotNetNuke.Modules.ActiveForums.ForumBase.get_CanCreate()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.ParseControls(String Template)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.BindTopics(String TopicsTemplate)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicsView.OnLoad(EventArgs e)"
```

**Comment by johnhenley** [comment]
Hi @valadas thanks for reporting this. Never a good way to start the week ;) but any bug report is better than an unreported bad install experience 😀 
I will investigate.

**Comment by johnhenley** [comment]
@valadas if you "restart application" does it work ok or do you keep getting errors?

**Comment by valadas** [comment]
@johnhenley The issue does persist after an app restart

**Comment by johnhenley** [comment]
@valadas do you remember if when you were adding the module, you were able to "place" the module like this:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/f5a055b6-3a34-493b-be7f-768a64e610ca)

Or when you added it, did it go straight to this:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/ea6d0af5-d0de-43a9-9728-f22317f2deeb)

**Comment by johnhenley** [comment]
Also, could you post a screenshot of the first 10 rows of activeforums_Settings table from SQL ?

**Comment by valadas** [comment]
I was able to place the module correctly the way you showed.

Here are my settings:

| ModuleId | GroupKey | SettingName                | SettingValue                    |
|----------|----------|----------------------------|---------------------------------|
| 385      | F:-1     | ALLOWRSS                   | false                           |
| 385      | F:-1     | REPLYFORMID                | 0                               |
| 385      | F:-1     | TOPICFORMID                | 0                               |
| 385      | F:-1     | TOPICSTEMPLATEID           | 0                               |
| 385      | F:-1     | TOPICTEMPLATEID            | 0                               |
| 385      | G:1      | ALLOWATTACH                | true                            |
| 385      | G:1      | ALLOWEMOTICONS             | true                            |
| 385      | G:1      | ALLOWHTML                  | true                            |
| 385      | G:1      | ALLOWLIKES                 | true                            |
| 385      | G:1      | ALLOWPOSTICON              | true                            |
| 385      | G:1      | ALLOWRSS                   | true                            |
| 385      | G:1      | ALLOWSCRIPT                | false                           |
| 385      | G:1      | ATTACHALLOWBROWSESITE      | true                            |
| 385      | G:1      | ATTACHCOUNT                | 3                               |
| 385      | G:1      | ATTACHINSERTALLOWED        | false                           |
| 385      | G:1      | ATTACHMAXHEIGHT            | 450                             |
| 385      | G:1      | ATTACHMAXSIZE              | 1000                            |
| 385      | G:1      | ATTACHMAXWIDTH             | 450                             |
| 385      | G:1      | ATTACHTYPEALLOWED          | txt,tiff,pdf,xls,xlsx,doc,docx,ppt,pptx |
| 385      | G:1      | AUTOTRUSTLEVEL             | 0                               |
| 385      | G:1      | CONVERTINGTOJPEGALLOWED    | false                           |
| 385      | G:1      | DEFAULTTRUSTLEVEL          | 0                               |
| 385      | G:1      | EDITORHEIGHT               | 350                             |
| 385      | G:1      | EDITORMOBILE               | 2                               |
| 385      | G:1      | EDITORSTYLE                | 2                               |
| 385      | G:1      | EDITORTOOLBAR              | bold,italic,underline,quote    |
| 385      | G:1      | EDITORTYPE                 | 2                               |
| 385      | G:1      | EDITORWIDTH                | 99%                             |
| 385      | G:1      | EMAILADDRESS               |                                 |
| 385      | G:1      | INDEXCONTENT               | true                            |
| 385      | G:1      | ISMODERATED                | false                           |
| 385      | G:1      | MAXATTACHHEIGHT            | 800                             |
| 385      | G:1      | MAXATTACHWIDTH             | 800                             |
| 385      | G:1      | MODAPPROVETEMPLATEID       | 0                               |
| 385      | G:1      | MODDELETETEMPLATEID        | 0                               |
| 385      | G:1      | MODMOVETEMPLATEID          | 0                               |
| 385      | G:1      | MODNOTIFYTEMPLATEID        | 0                               |
| 385      | G:1      | MODREJECTTEMPLATEID        | 0                               |
| 385      | G:1      | PROFILETEMPLATEID          | 1                               |
| 385      | G:1      | QUICKREPLYFORMID           | 7                               |
| 385      | G:1      | REPLYFORMID                | 6                               |
| 385      | G:1      | TOPICFORMID                | 5                               |
| 385      | G:1      | TOPICSTEMPLATEID           | 3                               |
| 385      | G:1      | TOPICTEMPLATEID            | 4                               |
| 385      | G:1      | USEFILTER                  | true                            |

**Comment by johnhenley** [comment]
@thanz

> I was able to place the module correctly the way you showed.
> 
> Here are my settings:
> 
> ModuleId	GroupKey	SettingName	SettingValue
> 385	F:-1	ALLOWRSS	false
> 385	F:-1	REPLYFORMID	0
> 385	F:-1	TOPICFORMID	0
> 385	F:-1	TOPICSTEMPLATEID	0
> 385	F:-1	TOPICTEMPLATEID	0
> 385	G:1	ALLOWATTACH	true
> 385	G:1	ALLOWEMOTICONS	true
> 385	G:1	ALLOWHTML	true
> 385	G:1	ALLOWLIKES	true
> 385	G:1	ALLOWPOSTICON	true
> 385	G:1	ALLOWRSS	true
> 385	G:1	ALLOWSCRIPT	false
> 385	G:1	ATTACHALLOWBROWSESITE	true
> 385	G:1	ATTACHCOUNT	3
> 385	G:1	ATTACHINSERTALLOWED	false
> 385	G:1	ATTACHMAXHEIGHT	450
> 385	G:1	ATTACHMAXSIZE	1000
> 385	G:1	ATTACHMAXWIDTH	450
> 385	G:1	ATTACHTYPEALLOWED	txt,tiff,pdf,xls,xlsx,doc,docx,ppt,pptx
> 385	G:1	AUTOTRUSTLEVEL	0
> 385	G:1	CONVERTINGTOJPEGALLOWED	false
> 385	G:1	DEFAULTTRUSTLEVEL	0
> 385	G:1	EDITORHEIGHT	350
> 385	G:1	EDITORMOBILE	2
> 385	G:1	EDITORSTYLE	2
> 385	G:1	EDITORTOOLBAR	bold,italic,underline,quote
> 385	G:1	EDITORTYPE	2
> 385	G:1	EDITORWIDTH	99%
> 385	G:1	EMAILADDRESS	
> 385	G:1	INDEXCONTENT	true
> 385	G:1	ISMODERATED	false
> 385	G:1	MAXATTACHHEIGHT	800
> 385	G:1	MAXATTACHWIDTH	800
> 385	G:1	MODAPPROVETEMPLATEID	0
> 385	G:1	MODDELETETEMPLATEID	0
> 385	G:1	MODMOVETEMPLATEID	0
> 385	G:1	MODNOTIFYTEMPLATEID	0
> 385	G:1	MODREJECTTEMPLATEID	0
> 385	G:1	PROFILETEMPLATEID	1
> 385	G:1	QUICKREPLYFORMID	7
> 385	G:1	REPLYFORMID	6
> 385	G:1	TOPICFORMID	5
> 385	G:1	TOPICSTEMPLATEID	3
> 385	G:1	TOPICTEMPLATEID	4
> 385	G:1	USEFILTER	true

@valadas  thanks!
Could you also send the contents of activeforums_Forums and activeforums_Groups?
It looks like there is some rogue data in here:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/e71c96fe-b370-4024-8371-3cd1978f3686)

**Comment by valadas** [comment]
Well, I destroyed that instance and started over and could no longer reproduce the issue... Everything happens to work fine so far. Maybe that instance was not as clean as I thought...
