### ISSUE TITLE
Code is not being displayed

### ISSUE THREAD

**Issue by Tychodewaard** [DNNCommunity/Dnn.CommunityForums#87]
## Describe the bug
I wanted to paste the following code on the forums.
<button onclick="goBack()">Go Back</button>

<script>
function goBack() {
  window.history.back();
}
</script>

But this resulted in empty space in the forums.

DNN 9.9.1 
Active Forums 6.5.1.

**Comment by Timo-Breumelhof** [comment]
That should be fixed with the PR of this issue:
https://github.com/DNNCommunity/Dnn.CommunityForums/issues/73
I tested it locally and it works as expected.

We just need a new release :-)
