### ISSUE TITLE
ENH: Remove "Enterprise version" texts from RESX files?

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#872]
## Is your feature request related to a problem?
**Please describe.**
I see this:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/bd37f45e-1479-4045-af6e-f527af2bd5fc)

```
  <data name="[RESX:EnterpriseFeatures:Intro].Text" xml:space="preserve">
    <value>Features that might be necessary for high traffic sites.</value>
  </data>
  <data name="[RESX:EnterpriseFeatures].Text" xml:space="preserve">
    <value>Advanced  Features</value>
  </data>

```

## Describe the solution you'd like
I guess we can remove those, right? Or is there a secret Enterprise version I don't know about?

**Comment by johnhenley** [comment]
These can be removed. There is a larger task #484 for cleaning up RESX strings if anyone ever has free time.
