### ISSUE TITLE
Error: DNN Community Forums is currently unavailable. DotNetNuke.Services.Exceptions.ModuleLoadException: The ID 'plhPoll' is already used by another control. --->

### ISSUE THREAD

**Issue by gnossosp** [DNNCommunity/Dnn.CommunityForums#885]
## Software Versions
- DNN: v. 09.13.03
- Module: DNN Community forums 8.0.1

## To Reproduce
New Installation 
Open Forums>Sample Forum 1
Create a post
Add A Poll with two questions.
Add Quick Reply and submit

Error message thrown:
![Poll Error](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/72934916/d5d9009d-b8da-45e2-aae8-5c49494379cc)

## Expected behavior

Should be able to post polls and replies to poll.

## Error log
**Note: Debug DLL's**
Please replace the current extension DLL's with the debug DLL's (if these are available with the release) and reproduce the error with the debug DLL's before pasting the error log.

Paste the error log that is related to this issue.
ModuleId:666

ModuleDefId:162

FriendlyName:DNN Community Forums

ModuleControlSource:DesktopModules/ActiveForums/ActiveForums.ascx

AbsoluteURL:/Default.aspx

DefaultDataProvider:DotNetNuke.Data.SqlDataProvider, DotNetNuke

ExceptionGUID:ad2cf36b-e140-4c79-9d0a-d9ae2f2bd2da

AssemblyVersion:9.13.3

PortalId:0

UserId:1

TabId:146

RawUrl:/forum/aft/2

Referrer:https://domainnamehere.com/forum/aft/2

UserAgent:Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36

ExceptionHash:3LpIonC4WLmCvXDt09D0nXrqKPA=

Message:The ID 'plhPoll' is already used by another control.

StackTrace:

InnerMessage:The ID 'plhPoll' is already used by another control.

InnerStackTrace:

   at System.Web.UI.TemplateParser.ParseString(String text, VirtualPath virtualPath, Encoding fileEncoding)
   at System.Web.UI.TemplateParser.ParseInternal()
   at System.Web.UI.TemplateParser.Parse()
   at System.Web.UI.TemplateParser.ParseTemplateInternal(String content, VirtualPath virtualPath, Boolean ignoreFilter)
   at System.Web.UI.TemplateParser.ParseControl(String content, VirtualPath virtualPath, Boolean ignoreFilter)
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.BindTopic()
   at DotNetNuke.Modules.ActiveForums.Controls.TopicView.OnLoad(EventArgs e)
Source:

FileName:

FileLineNumber:0

FileColumnNumber:0

Method:

Server Name: win8122

**Comment by johnhenley** [comment]
@gnossosp thanks for posting. Hopefully we can get it triaged and fixed in 8.1.

**Comment by gnossosp** [comment]
I see this is closed YAY, has this been compiled into the release candidate? Sorry I don't know how the work flows. Thanks

**Comment by johnhenley** [comment]
> I see this is closed YAY, has this been compiled into the release candidate? Sorry I don't know how the work flows. Thanks

Not yet. It should be in the 8.1 release. If you want to do a fix on your own, it's just a template change.
