### ISSUE TITLE
Add reply: doesn't show CKEditor

### ISSUE THREAD

**Issue by wbonekamp** [DNNCommunity/Dnn.CommunityForums#887]
## Describe the bug
When I like to add a reply there's no CKEditor. Othe screen do sho the CKEditor

## Software Versions
- DNN: 8.0.1
- Module: 09.11.02

## To Reproduce
1. Go to Forum
2. Go to a topic
3. Click add reply
4. no editor visible

## Expected behavior
CK Editor

## Screenshots
![CKEditor](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/7567981/e64ed5a3-d1df-420d-9cf7-3d1198aede9c)
![CKEditorConsole](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/7567981/77db360d-8121-4681-b90b-ac2053211038)

## Error log
**Note: Debug DLL's**
Console log: /Providers/HtmlEditorProviders/DNNConnect.CKE/js/ckeditor/4.18.0/skins/moono-lisa/skin.js?t=M2G9 net::ERR_ABORTED 404 (Not Found)

**Comment by wbonekamp** [comment]
Hey Timo... it's a clean install... nothing has been been customized on the CKEditor...

**Comment by wbonekamp** [comment]
I agree it should be an issue in the configuration of DNN related to the CKEditor.... maybe a version issue (not compatible)

**Comment by wbonekamp** [comment]
Or Maybe an issue with the Smilies... it only shows the text "smilies" on the right of the text area...

**Comment by Timo-Breumelhof** [comment]
Hmm, strange.. can you try to upgrade DNN to 09.13.03?

**Comment by wbonekamp** [comment]
I don't see the smilies on the DNNCommunity forum... Doest it use a different theme (templates)?

**Comment by Timo-Breumelhof** [comment]
The icons are an option of the forum.

but.. can you try this template and see if that helps?

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/0273e978-8e6b-4c16-b962-725518a396da)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/6af9dfa2-2709-4d1a-83be-8e4672b859b8)

**Comment by Timo-Breumelhof** [comment]
@johnhenley this might be "TopicEditor.ascx" is missing

**Comment by johnhenley** [comment]
@wbonekamp if you put an html module that page, does it show ckeditor when you edit content?

If you just installed, go to control panel, forums, forum group 1, features tab. Turn off posticons and emoticons

**Comment by johnhenley** [comment]
Also the console error for ckeditor references something to do with pdf. You will need to resolve that.

**Comment by johnhenley** [comment]
@Timo-Breumelhof I don't think this is forums specific. Let's see if the html module works first. The templates are fine since the layout is showing buttons etc.

**Comment by wbonekamp** [comment]
Had to save the CKeditor Options for the page (without changing anything) and now it shows the editor.. thanks for the help!
