### ISSUE TITLE
Profile image Quality low

### ISSUE THREAD

**Issue by wbonekamp** [DNNCommunity/Dnn.CommunityForums#888]
## Describe the bug
Profile image low quality

## Software Versions
- DNN: 8.0.1
- Module: 09.11.3

## To Reproduce
add profile image

## Expected behavior
Where can I change/set the profile image quality?

## Screenshots
![ProfileImage](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/7567981/06ccec7e-8c8a-4771-819f-d57a028facb1)

## Error log
no errors in log

**Comment by wbonekamp** [comment]
Avatar size!!

**Comment by Timo-Breumelhof** [comment]
True see: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/421
