### ISSUE TITLE
Theme used on dnncommunity.org available?

### ISSUE THREAD

**Issue by puresystems** [DNNCommunity/Dnn.CommunityForums#92]
## Please summarize your question in one sentence
The dnncommunity.org forum appears to use an update theme which looks better than the default one. Is this available for download?

**Comment by david-poindexter** [comment]
@puresystems yes, you can find it [HERE](https://github.com/DNNCommunity/DNNCommunityTheme/tree/master/src/Templates/Blog/Community2019).

**Comment by Timo-Breumelhof** [comment]
Hmm, maybe @puresystems is talking about the Forum Theme? @david-poindexter

**Comment by hismightiness** [comment]
Oh...  If that's the case, then it's custom, and it's stored in the database.  Specifically, in the `activeforums_Templates` table.

**Comment by david-poindexter** [comment]
@Timo-Breumelhof the forum theme is inside the community theme and I linked to the proper directory within.  ;-)

**Comment by david-poindexter** [comment]
Oh wait - my mistake.  I got forums confused with the blog.  Sorry about that.  @hismightiness is correct.

**Comment by puresystems** [comment]
Sorry, yes we were looking for the active forum module theme - it's selected via the module settings and they appear to be stored in \DesktopModules\ActiveForums\themes - is it a mix of files and database entries?

**Comment by hismightiness** [comment]
> Sorry, yes we were looking for the active forum module theme - it's selected via the module settings and they appear to be stored in \DesktopModules\ActiveForums\themes - is it a mix of files and database entries?

That's the default theme.  Once you save a change, it's stored in the previously mentioned database table.  We inherited this architecture decision from Active Modules when DNN Corp acquired them years ago.

**Comment by puresystems** [comment]
I see, that makes sense now, thanks for everyones help.

**Comment by hismightiness** [comment]
![bitmoji](https://sdk.bitmoji.com/render/panel/d6ea9573-7b6b-4374-bcf8-3c38eb0b0972-1ddc1a2c-5392-4c1a-bc2f-0caa140e965b-v1.png?transparent=1&palette=1&width=246)

**Comment by Timo-Breumelhof** [comment]
Well, IMO it would be much better if the templates would be file based (organized in folders) as that would also make is easier to copy / change templates.

**Comment by hismightiness** [comment]
Agreed 100%, but that would need to be well-planned and implemented -  in a new issue.  Unfortunately, we already have the current architecture as a dependency.

**Comment by puresystems** [comment]
I would agree that files would be more useful. Razor templates would be great.

**Comment by Timo-Breumelhof** [comment]
https://github.com/DNNCommunity/Dnn.CommunityForums/issues/93

@puresystems Also switching to Razor would be much more work IMO.

**Comment by Timo-Breumelhof** [comment]
@puresystems Here's a copy of my file backup of the templates.
You need to copy the content of the HTML file in _html folder in the AF controlpanel
[Community2019.zip](https://github.com/DNNCommunity/Dnn.CommunityForums/files/7180829/Community2019.zip)

**Comment by hismightiness** [comment]
I believe that Razor templates would definitely lower the learning curve and be easier for an existing .NET developer to manage and work with, but I don't think it's the best option for a longer-term solution.  On larger, higher-traffic sites, this could present ongoing and increasing performance issues. A cached client-side approach might be better, but also have its own limitations.  

Anyhow, we should discuss the technical aspects of that in a new issue specifically created for implementing a new template solution.  :)

**Comment by puresystems** [comment]
> 
> 
> @puresystems Here's a copy of my file backup of the templates.
> You need to copy the content of the HTML files in _html folder in the AF controlpanel
> [Community2019.zip](https://github.com/DNNCommunity/Dnn.CommunityForums/files/7180829/Community2019.zip)

Thanks @Timo-Breumelhof, that's really helpfull and saved me some time!
