### ISSUE TITLE
Change Templates to Cached File based

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#93]
## Is your feature request related to a problem?
**Please describe.**
Editing and testing Forum Templates is cumbersome because the templates are in the database.
File based templates would make creating templates much easier.

The reason I think templates should be file based are the following:

- Portability
- Simplicity
- Editability
- Versioning

Creating a template for the module is a real pain ATM.
The module gets the default templates from file (“ActiveForums\config\templates”)
When you create a custom template these are stored mainly partly in the database and partly in “ActiveForums\themes”.
(where there's also a Module.css which we should get rid of IMO as it has way too specific CSS)
For editing you need to go into the edit screen in the module and edit your ascx there, and many time you need to restart DNN for your change to be picked up.

I started creating a Bootstrap 4 template for dnncommunity.org a long time ago and it took me at least 3 to 4 times as long due to constantly having to restart the DNN and the cumbersome edit interface for templates.
And then when I wanted to move them from my local machine to the live site, I had to copy them one by one into the edit screen and also save some separate txt file to be able to put them in versioning somehow.
Not very good for my motivation ATT if I'm honest, way too many hoops to jump through...

File based templates from a single folder (so there's not some random CSS you need to overwrite) would make the creation of Templates way more efficient and also fun TBH. :-)

Also, some people asked for these templates and they are currently much more difficult to share compared to a simple file based approach. See: https://github.com/DNNCommunity/Dnn.CommunityForums/issues/92

I think we could offer 3 possible locations:

For the default templates that come with the module:

- /Desktopmodules/AciveForums/Tempaltes

We should however add a note to these templates that they should not be edited.?
(overwrite on upgrade)

- Portals/_Default/ActiveForums/Templates > For all all portals
- Portals/PortalFolder/ActiveForums/Templates > a specific folder

## Describe the solution you'd like
Load the templates (*.ascx)  form a "templatename" folder.

**Comment by hismightiness** [comment]
I was just about to do this...  :D

**Comment by johnhenley** [comment]
> But I do think we need some kind of debug mode in the module too as clearing the DNN cache for every template change kind of sucks..

Perhaps cache settings for the module are ignored?

**Comment by johnhenley** [comment]
> But I do think we need some kind of debug mode in the module too as clearing the DNN cache for every template change kind of sucks..

I created an issue to review module cache settings

**Comment by WillStrohl** [comment]
Related Issue, should this issue get worked on, it should also keep in mind Issue #97.

**Comment by johnhenley** [comment]
Questions for the community. Please comment if you have an opinion. 

- Is moving templates to files acceptable as a breaking change? If clear instructions are provided as part of an upgrade on _how, what, and where_ to move things, is that good enough? Or does this need to be done automatically as part of an upgrade? 
- Do you consider templates to be separate and distinct from themes, or are templates just one part of a theme?
- If existing templates are moved to files using the template name as file name that means template names must be unique. Is that an issue for anyone?

**Comment by johnhenley** [comment]
For option B, should
~/portals/_default/activeforums_themes/bootstrap4/custom/theme.css
REPLACE or ADD to parent
~/portals/_default/activeforums_themes/bootstrap4/theme.css
________________________________

**Comment by WillStrohl** [comment]
That's a good question...  I think we'd want to replace, but I'll defer to @Timo-Breumelhof on this one.

**Comment by Timo-Breumelhof** [comment]
@johnhenley @WillStrohl 
Yes good question :-)

Difficult to answer..

We are providing this option for the use case that someone wants to create a color variation of a template.
I think that if you would want to change a lot, also layout, you'll probably copy the folder and create your own template.

I'm not a fan of overwriting existing values with a custom style sheet TBH. (which would rule against adding)
But it can also get cumbersome if ~/portals/_default/activeforums_themes/bootstrap4/theme.css would change (not the colors something in the layout) and you would have to incorporate that into your in ~/portals/_default/activeforums_themes/bootstrap4/custom/theme.css

What to you guys think? I tend to lean towards replace.. ?

**Comment by Timo-Breumelhof** [comment]
FYI, I edited my previous comment

**Comment by WillStrohl** [comment]
I agree with that, Timo...  That sounds like a less annoying experience for designers, and we should always look at these updates in a way that also incorporates the way people will feel when interacting with these updates later.  That will directly impact overall long-term adoption and usage.

**Comment by johnhenley** [comment]
> I think ADD is better.
>
I agree it should be ADD so that you're not duplicating the base theme.css file in your custom version. You're only customizing the things need to override.
