### ISSUE TITLE
ENH: More mobile UI improvements

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#932]
Over the past few releases, DNN Community Forums has HUGE improvements on UI, particularly on mobile. Here are a few quick things we could do to make it even better….
 
- Remove “Search Forums” text; just leave the magnifying glass;

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/1f4bef8a-f13a-45b5-bfab-080ec5e1171d)

- Don’t show “Sort: option” on mobile.
- Get rid of the ocean of space in the profile section on mobile.
 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/902b69db-fd37-48eb-9c49-349f85f2432f)

- Don’t show ‘Search’ box on mobile.
- Don’t show the ratings icons on mobile.
- Figure out the funky icon issue.

- Replace the ‘you are not authorized’ with a login link (we did this in topic view; do same in topics view)
 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/def85729-558f-45a4-9223-e6eacaeead72)

**Comment by johnhenley** [comment]
@Timo-Breumelhof i will do this: Replace the ‘you are not authorized’ with a login link

**Comment by Timo-Breumelhof** [comment]
@johnhenley moved 

`- “Next >” – should be right-justified. `

to a separate issue as it' not only a Mobile Issue I just saw.

**Comment by Timo-Breumelhof** [comment]
@johnhenley the spacing issue was IMO due to the wrong templates being selected (default instead of the Theme ones)

**Comment by johnhenley** [comment]
> @Timo-Breumelhof i will do this: Replace the ‘you are not authorized’ with a login link 

@Timo-Breumelhof the login link added in #1004

**Comment by johnhenley** [comment]
closing as resolved via #1004, and additional issues opened (#787, #939)
