### ISSUE TITLE
Paging does not work

### ISSUE THREAD

**Issue by MaiklT** [DNNCommunity/Dnn.CommunityForums#933]
## Describe the bug
When I try to navigate to page 2,3,... I am always landing on page 1 of a thread

## Software Versions
- DNN: 09.13.03
- Module: 08.01

## To Reproduce
1. Go to [this thread](https://dnncommunity.org/forums/using-dnn/extensions/document-viewer-module/)
2. Click on 2, 3, > or >>

## Expected behavior
Move to expected page

## Browser
- Edge
- Firefox

**Comment by johnhenley** [comment]
@MaiklT 

I have quickly tested this and not seeing this issue. Tested several topics like this one:

https://dnncommunity.org/forums/using-dnn/admin-and-config/33/

**Comment by johnhenley** [comment]
@MaiklT can you check on "my settings" and what setting you have for "items per page"?

**Comment by MaiklT** [comment]
> @MaiklT can you check on "my settings" and what setting you have for "items per page"?
5

**Comment by MaiklT** [comment]
> @MaiklT
> 
> I have quickly tested this and not seeing this issue. Tested several topics like this one:
> 
> https://dnncommunity.org/forums/using-dnn/admin-and-config/33/

No, it is not in forum, it is in the thread.

**Comment by johnhenley** [comment]
@MaiklT I set my items to page to 5. Testing this one from iPhone and no issues but will test further:
https://dnncommunity.org/forums/using-dnn/admin-and-config/cant-add-new-users-with-my-superuser-account/3/
