### ISSUE TITLE
ENH: community-default theme shows extra icon

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#937]
## Is your feature request related to a problem?
On the community site there's an issue with the Icons:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/34b4e23b-6d23-404c-8d13-2460a9682de3)

This is from TopicsView

That's weird because on my local test site this is not visible:

----------------------------------------------
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/592118ed-25f4-4cfd-bccf-5b938e2bffd8)

## Describe the solution you'd like
Fix is :-)

**Comment by Timo-Breumelhof** [comment]
HTML:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/2a03cbd0-ef9b-46d1-92cb-983ffa2f5854)

**Comment by Timo-Breumelhof** [comment]
not the resource file..

https://github.com/DNNCommunity/Dnn.CommunityForums/blob/8d57f485d63682a6583f4ef5b79483fcd715b50e/Dnn.CommunityForums/App_LocalResources/SharedResources.resx#L1675

**Comment by Timo-Breumelhof** [comment]
So I guess it;s this &nbsp; we see, but why?

https://github.com/DNNCommunity/Dnn.CommunityForums/blob/8d57f485d63682a6583f4ef5b79483fcd715b50e/Dnn.CommunityForums/themes/community-default/templates/TopicsView.ascx#L13C158-L13C164

**Comment by Timo-Breumelhof** [comment]
@johnhenley right, but why is the space parsed to something else?

**Comment by Timo-Breumelhof** [comment]
@johnhenley Hmm @WillStrohl edited a file on the server.. maybe it was this one.. I'll check the server

**Comment by Timo-Breumelhof** [comment]
@johnhenley 

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/79516d75-1e22-4055-a95f-136cfe5e7ea6)

**Comment by johnhenley** [comment]
I think you're onto something ...

Hang on.

This is what it looks like encoded:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/5e35c62f-a8c9-4fec-ad19-ccedaed458be)

And this is a stackoverflow answer about that character sequence 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/ebb84893-5811-4413-a220-d7fbaea313d8)

If you edit from the control panel (not an editor), replace the unprintable character with `&nbsp;`

**Comment by Timo-Breumelhof** [comment]
@johnhenley I edited it on the server and replaced the char with &nbsp;, cleared the cache and now it's "fixed"

**Comment by Timo-Breumelhof** [comment]
@johnhenley but now check out what the CP editor does:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/ab35b2cd-a1d0-4aa9-a68c-76609ec58a6e)

It interprets the `&nbsp;` I think..?

**Comment by Timo-Breumelhof** [comment]
Yes, saving replaces &nbsp; with the "character"

**Comment by Timo-Breumelhof** [comment]
@johnhenley I'll create another issue for the cause of this

**Comment by WillStrohl** [comment]
Whoa... Nice find!
