### ISSUE TITLE
Integrate DNN Search

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#94]
## Is your feature request related to a problem?
The Forum Content does not get indexed by DNN Search

## Describe the solution you'd like
Integrate the (once new) DNN Search.
See also: https://github.com/ActiveForums/ActiveForums/issues/12

**Comment by Timo-Breumelhof** [comment]
FYI, we have a client that was going to sponsor this feature, but unfortunately the client decided the internal Forum Search is enough.

**Comment by WillStrohl** [comment]
We're going to keep this issue, though.  It's a great idea and should be done whenever we can.  :)

**Comment by Timo-Breumelhof** [comment]
Agreed
