### ISSUE TITLE
ENH: Add button on top of TopicsView

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#941]
## Is your feature request related to a problem?
Both Theme's lack an [Add Topic] button at the top of TopicView.ascx

## Describe the solution you'd like
Add one :-)

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/4d905475-af17-46a1-8407-dcb62bb65cca)

Better:

![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/8999382/60a31ba3-9da7-4af8-94ab-e3acd56511f8)

**Comment by Timo-Breumelhof** [comment]
FYI, I already copied the change to the community-default Theme to the community site @WillStrohl @johnhenley

**Comment by WillStrohl** [comment]
@Timo-Breumelhof @johnhenley Should I process this, or is it waiting on something?

**Comment by johnhenley** [comment]
> @Timo-Breumelhof @johnhenley Should I process this, or is it waiting on something?
After @Timo-Breumelhof  changed this directly, the search box crept over...
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/2a667620-26ed-4e41-bc29-4a2df1e09f81)
