### ISSUE TITLE
BUG: Can't mark question answered

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/Dnn.CommunityForums#945]
## Describe the bug
I went to the community site in hopes to cleanup the "Unanswered" forums posts and could not make the answer.

## Software Versions
- DNN: 9.13.3
- Module: 8.1.0

## To Reproduce
1. Go to https://dnncommunity.org and login as a user that is a forum moderator.
2. Go to https://dnncommunity.org/forums
2. Click on 'Filtered Topics'
3. Click on 'Unresolved'
4. Go to any question that has at least a reply
5. Click on the "Correct Answer" link
6. An error shows (see screenshot)

## Expected behavior
The question should now be marked as resolved and no long show in the Unresolved list.

## Screenshots
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/6371568/759f118c-4f48-4127-b0c4-504206b4f64a)

**Comment by johnhenley** [comment]
@valadas thanks for reporting. Nothing worse than saying "it's fixed" and someone saying "um, no" ;)
