### ISSUE TITLE
ENH: Informative posts should not be listed in "Unanswered"

### ISSUE THREAD

**Issue by valadas** [DNNCommunity/Dnn.CommunityForums#946]
## Describe the bug
If a post is informative (like an announcement or such), it should probably not be listed in the "Unanswered" list as this would be a list I would look at to potentially find someone to help out on a question.

## Software Versions
- DNN: 9.13.3
- Module: 8.1.0

**Comment by Timo-Breumelhof** [comment]
Agreed
