### ISSUE TITLE
BUG: User display name missing from reply email notification

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.CommunityForums#947]
## Describe the bug
The email notifications for forum post replies now are missing the user's display name.

## Software Versions
- DNN: 09.13.03
- Module: 08.01.00

## To Reproduce
1. Subscribe to a forum post
2. Receive an email notification due to a forum post reply
3. See missing user display name in left column of table

## Expected behavior
Display name for the user replying to the forum post should be in the email notification.

## Screenshots
Sample email:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4568451/f37725ef-3476-474f-88a2-c323f46d7cfa)

Post on website:
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/4568451/a19d3d87-b864-4e99-aced-466359c1491b)

## Error log
n/a

## Additional context
This information was in the email notifications prior to the latest release.

**Comment by Timo-Breumelhof** [comment]
@david-poindexter thank you for reporting this. I think this one #923  is the same issue and @johnhenley already fixed it for 08.01.01

**Comment by johnhenley** [comment]
> @david-poindexter thank you for reporting this. I think this one #923  is the same issue and @johnhenley already fixed it for 08.01.01 

Duplicate #923

**Comment by david-poindexter** [comment]
So sorry for yet another duplicate - I need to be more diligent in searching existing issues.  🤦🏼

**Comment by johnhenley** [comment]
> So sorry for yet another duplicate - I need to be more diligent in searching existing issues.  🤦🏼 

No problem at all. The more people we have, the better:)
