### ISSUE TITLE
Flood control is for all users, also Admins

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#95]
The flood control setting is for all users even site administrators.
So even as a host you are not allowed to post more often than every x seconds, which is a bit weird.
IMO admin users or even better users that have:

ModApprove | ModMove | ModSplit | ModDelete | ModUser | ModEdit | ModLock | ModPin

Rights should be excluded from the flood interval

**Comment by hismightiness** [comment]
I just want to be sure I understand what needs to be done here...  Are you saying that this issue should be to exclude Administrators and Superusers from the flood protection setting?

**Comment by Timo-Breumelhof** [comment]
Yes, or all users with Approve Thread rights?

**Comment by hismightiness** [comment]
Is there any concern that we might be opening up flooding from a compromised account?  For example, if someone's computer or user account is compromised and another person begins to post on their behalf.

**Comment by Timo-Breumelhof** [comment]
Well if you have moderate rights don't really see the issue?

**Comment by hismightiness** [comment]
Agreed.  I'm just throwing thoughts out there.  The scenario I'm worried about is not as common, I know.  :)
