### ISSUE TITLE
ENH: Excess whitespace on mobile devices for Filtered topics drop-down

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#959]
On mobile devices, text is not shown. Remove extra whitespace or show text. 
![image](https://github.com/DNNCommunity/Dnn.CommunityForums/assets/9553126/9d36316d-47f6-4a83-8b87-f4ba5728a6b5)

**Comment by Timo-Breumelhof** [comment]
@johnhenley Good catch :-)

**Comment by johnhenley** [comment]
@Timo-Breumelhof I think I posted the issue too quickly and not clearly. What should happen on mobile is just show the icon without the text. The screenshot I included was to show that there is extra whitespace where the text would be. I think for mobile we should just show the icon/get rid of the whitespace and not show any text. That is consistent with the way the toolbars behave on mobile. Which is great BTW.
