### ISSUE TITLE
BUG: Redirect after editing a post comment

### ISSUE THREAD

**Issue by david-poindexter** [DNNCommunity/Dnn.CommunityForums#962]
## Describe the bug
When editing a post comment, clicking "Submit" stays on the same page/control.

## Software Versions
- DNN: 09.13.03
- Module: 08.01.01

## To Reproduce
1. Edit your own comment within a forum post
2. Make changes to your comment
3. Click "Submit"
4. See unexpected behavior

## Expected behavior
It should save the changes and redirect to the forum post containing the comment being edited.

## Screenshots
n/a

## Error log
n/a

## Additional context
n/a

**Comment by johnhenley** [comment]
Ugh. I swear I fixed that yesterday :)
