### ISSUE TITLE
Long Word hyphenation or Column span for topics 

### ISSUE THREAD

**Issue by gnossosp** [DNNCommunity/Dnn.CommunityForums#985]
DNN: 09.13.03
Dnn Com Forum: 8.1.2
Com Forum Theme
Template/Theme issue
## Is your feature request related to a problem?
 
Posts in full screen in topics view have content shown in first column and there is no accounting for hyphenation of long words.  This issue goes away on smaller screen sizes where the content is hidden. 

## Describe the solution you'd like
Could the template be modified to have content span entire page in Topics View by default?
I know the content is truncated, but an alternate (but not as desirable solution) can we shorten the content shown to a lot fewer characters?

![Clipboard_07-12-2024_01_hypnens](https://github.com/user-attachments/assets/d8956121-8a73-4072-9dbc-380c3ef9b676)

**Comment by Timo-Breumelhof** [comment]
It's a table so there currently is no easy way to make the text expand to being wider.

There is some CSS to prevent the text from taking up too much space, you can tweak that to your needs:

```
.dnn-community-forums .dcf-topics-view .dcf-topics .dcf-subject .dcf-topic-description {
	
	max-height: 4.8em;

}
```

You can add that to \DesktopModules\ActiveForums\themes\community-custom\custom\theme.css without the risk of it  being overwritten by an update

**Comment by gnossosp** [comment]
I've also tweaked the CSS to solve  the weirdness with the word wrap and awkward line/word breaks.
...
hyphens: auto;
...
