### ISSUE TITLE
BUG: Moderator Buttons not styled correctly

### ISSUE THREAD

**Issue by johnhenley** [DNNCommunity/Dnn.CommunityForums#995]
## Describe the bug

Moderator Buttons not styled correctly

## Software Versions
- DNN: 09.13.03
- Module: 08.01.02

## Expected behavior
Correct styling

## Screenshots
![image](https://github.com/user-attachments/assets/cbcee36d-5a1a-43e0-bd7f-c057ecadf424)

**Comment by Timo-Breumelhof** [comment]
Hello @johnhenley thank you for logging this issue.
Unfortunately this is a duplicate of #969 
hehehe ;-)

**Comment by Timo-Breumelhof** [comment]
@johnhenley I closed #969

**Comment by Timo-Breumelhof** [comment]
@johnhenley see PR #1000
