### ISSUE TITLE
ENH: Improve the way "Forum is moderated" message is displayed

### ISSUE THREAD

**Issue by Timo-Breumelhof** [DNNCommunity/Dnn.CommunityForums#999]
## Is your feature request related to a problem?
The message users see when they post in a moderated forum looks a bit wonky, that could be improved.

**Please describe.**
![image](https://github.com/user-attachments/assets/8eb867a0-25a1-4c20-9238-5bcb29db9512)

## Describe the solution you'd like
Make it look better

**Comment by johnhenley** [comment]
@Timo-Breumelhof do you mean layout/styling or the wording?

**Comment by Timo-Breumelhof** [comment]
@johnhenley for now layout

**Comment by Timo-Breumelhof** [comment]
@johnhenley This seems to come from D:Dnn.CommunityForums\controls\af_confirmaction.ascx
Shall I modernize the HTML?

**Comment by johnhenley** [comment]
Only if it's easy. I wouldn't spend more than an hour on it.

**Comment by Timo-Breumelhof** [comment]
![image](https://github.com/user-attachments/assets/a80dd557-2fe6-4325-8b3e-ca9f8bde2f78)
